# Generated by Django 5.2.8 on 2025-11-25 01:00

import django.db.models.deletion
import users.managers.custom_user
import users.models.custom_user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime', verbose_name='更新时间')),
                ('username', models.CharField(default=users.models.custom_user._generate_username, help_text='【业务说明】认证体系主键；【用法】系统自动生成；【示例】user_abcd1234;【参数】无；【返回值】str', max_length=150, unique=True, verbose_name='系统用户名')),
                ('phone', models.CharField(blank=True, help_text='【业务说明】非患者账号的主要登录凭据；【用法】医生/销售/助理需填写；【示例】13800138000;【参数】字符串;【返回值】str', max_length=15, null=True, unique=True, verbose_name='登录手机号')),
                ('wx_openid', models.CharField(blank=True, help_text='【业务说明】C 端患者/家属绑定的 OpenID；【用法】仅 user_type=1 需要；【示例】oUpF80Mh3VQW...;【参数】str;【返回值】str', max_length=64, null=True, unique=True, verbose_name='微信 OpenID')),
                ('wx_unionid', models.CharField(blank=True, help_text='【业务说明】多应用打通的 UnionID；【用法】用于后续拓展；【示例】ou123456789;【参数】str;【返回值】str', max_length=64, null=True, unique=True, verbose_name='微信 UnionID')),
                ('wx_nickname', models.CharField(blank=True, help_text='【业务说明】展示在聊天、工作室等场景的昵称；【用法】同步微信昵称或人工录入；【示例】张同学;【参数】str;【返回值】str', max_length=64, verbose_name='微信昵称')),
                ('wx_avatar_url', models.URLField(blank=True, help_text='【业务说明】头像 URL；【用法】前端直接展示；【示例】https://example.com/avatar.png;【参数】URL 字符串;【返回值】str', max_length=500, verbose_name='头像 URL')),
                ('is_subscribe', models.BooleanField(default=False, help_text='【业务说明】记录是否关注公众号；【用法】用于模板消息推送判断；【示例】True;【参数】bool;【返回值】bool', verbose_name='是否关注公众号')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, '患者/家属'), (2, '主治医生'), (3, '销售专员'), (4, '平台管理员'), (5, '医生助理')], default=1, help_text='【业务说明】划分账号角色；【用法】创建时指定；【示例】用户类型=医生；【参数】整数枚举；【返回值】int', verbose_name='用户类型')),
                ('is_active', models.BooleanField(default=True, help_text='【业务说明】控制账号启用状态；【用法】禁用违规用户；【示例】False 表示冻结；【参数】bool;【返回值】bool', verbose_name='是否启用')),
                ('is_staff', models.BooleanField(default=False, help_text='【业务说明】标识后台可登录管理员站点；【用法】授予运营或管理员；【示例】True;【参数】bool;【返回值】bool', verbose_name='后台权限')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='【业务说明】账号注册时间；【用法】统计新增；【示例】2025-01-01 10:00;【参数】无;【返回值】datetime', verbose_name='注册时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
            },
            managers=[
                ('objects', users.managers.custom_user.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AssistantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime', verbose_name='更新时间')),
                ('name', models.CharField(help_text='【业务说明】助理姓名；【用法】聊天等处展示；【示例】张助理；【参数】str；【返回值】str', max_length=50, verbose_name='助理姓名')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '在职'), (2, '离职')], default=1, help_text='【业务说明】在职/离职标记；【用法】控制是否可接收任务；【示例】1=在职；【参数】枚举；【返回值】int', verbose_name='助理状态')),
                ('work_phone', models.CharField(blank=True, help_text='【业务说明】工作联系电话；【用法】医生可快速拨号；【示例】021-88888888；【参数】str；【返回值】str', max_length=20, verbose_name='工作电话')),
                ('joined_at', models.DateField(blank=True, help_text='【业务说明】入职日期；【用法】人事统计；【示例】2024-09-01；【参数】date；【返回值】date', null=True, verbose_name='入职日期')),
                ('user', models.OneToOneField(help_text='【业务说明】助理账号；【用法】user_type=助理；【示例】CustomUser#40；【参数】外键；【返回值】CustomUser', on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to=settings.AUTH_USER_MODEL, verbose_name='助理账号')),
            ],
            options={
                'verbose_name': 'Assistant Profile',
                'verbose_name_plural': 'Assistant Profiles',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime', verbose_name='更新时间')),
                ('name', models.CharField(help_text='【业务说明】医生姓名；【用法】前端展示；【示例】张主任；【参数】str；【返回值】str', max_length=50, verbose_name='医生姓名')),
                ('hospital', models.CharField(help_text='【业务说明】所属医院；【用法】展示/筛选；【示例】上海市第一人民医院；【参数】str；【返回值】str', max_length=100, verbose_name='所属医院')),
                ('department', models.CharField(help_text='【业务说明】所属科室；【用法】帮助患者识别；【示例】肿瘤科；【参数】str；【返回值】str', max_length=50, verbose_name='所属科室')),
                ('title', models.CharField(blank=True, help_text='【业务说明】职称；【用法】宣传素材；【示例】主任医师；【参数】str；【返回值】str', max_length=50, verbose_name='职称')),
                ('managed_patient_count', models.PositiveIntegerField(default=0, help_text='【业务说明】统计指标：当前在管患者量；【用法】大屏展示；【示例】88；【参数】int；【返回值】int', verbose_name='在管患者数')),
                ('user', models.OneToOneField(help_text='【业务说明】医生登录账号；【用法】user_type=医生；【示例】CustomUser#30；【参数】外键；【返回值】CustomUser', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='医生账号')),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profiles',
            },
        ),
        migrations.CreateModel(
            name='DoctorAssistantMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime', verbose_name='更新时间')),
                ('assistant', models.ForeignKey(help_text='【业务说明】提供服务的助理；【用法】必填；【示例】AssistantProfile#6；【参数】外键；【返回值】AssistantProfile', on_delete=django.db.models.deletion.CASCADE, related_name='assistant_doctor_links', to='users.assistantprofile', verbose_name='助理')),
                ('doctor', models.ForeignKey(help_text='【业务说明】被服务的医生；【用法】必填；【示例】DoctorProfile#2；【参数】外键；【返回值】DoctorProfile', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assistant_links', to='users.doctorprofile', verbose_name='医生')),
            ],
            options={
                'verbose_name': 'Doctor Assistant Mapping',
                'verbose_name_plural': 'Doctor Assistant Mapping',
            },
        ),
        migrations.AddField(
            model_name='assistantprofile',
            name='doctors',
            field=models.ManyToManyField(blank=True, help_text='【业务说明】助理支持的医生列表；【用法】通过 doctor_assistant_map 维护；【示例】多对多；【参数】M2M；【返回值】QuerySet', related_name='assistants', through='users.DoctorAssistantMap', to='users.doctorprofile', verbose_name='负责医生'),
        ),
        migrations.CreateModel(
            name='DoctorStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime', verbose_name='更新时间')),
                ('name', models.CharField(help_text='【业务说明】工作室对外名称；【用法】展示；【示例】张主任肺癌工作室；【参数】str；【返回值】str', max_length=50, verbose_name='工作室名称')),
                ('code', models.CharField(help_text='【业务说明】内部唯一编码，用于生成二维码；【用法】不可重复；【示例】STU001；【参数】str；【返回值】str', max_length=20, unique=True, verbose_name='工作室编码')),
                ('qr_code_url', models.URLField(blank=True, help_text='【业务说明】二维码图片地址；【用法】前端展示下载；【示例】https://cdn/qrcode.png；【参数】URL；【返回值】str', max_length=255, verbose_name='二维码地址')),
                ('intro', models.TextField(blank=True, help_text='【业务说明】工作室简介；【用法】介绍服务内容；【示例】专注肺癌精准康复；【参数】text；【返回值】str', verbose_name='工作室介绍')),
                ('owner_doctor', models.ForeignKey(help_text='【业务说明】工作室负责人；【用法】必须指定；【示例】DoctorProfile#1；【参数】外键；【返回值】DoctorProfile', on_delete=django.db.models.deletion.CASCADE, related_name='owned_studios', to='users.doctorprofile', verbose_name='负责人')),
            ],
            options={
                'verbose_name': 'Doctor Studio',
                'verbose_name_plural': 'Doctor Studios',
            },
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='studio',
            field=models.ForeignKey(blank=True, help_text='【业务说明】该医生所属工作室；【用法】展示二维码等；【示例】Studio#1；【参数】外键；【返回值】DoctorStudio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='users.doctorstudio', verbose_name='所属工作室'),
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime', verbose_name='更新时间')),
                ('phone', models.CharField(help_text='【业务说明】档案唯一锚点；【用法】销售查重或医生联系；【示例】13800138000；【参数】str；【返回值】str', max_length=15, unique=True, verbose_name='患者联系电话')),
                ('name', models.CharField(default='未命名患者', help_text='【业务说明】患者真实姓名；【用法】前端展示及医生沟通；【示例】王女士；【参数】str；【返回值】str', max_length=50, verbose_name='患者姓名')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, help_text='【业务说明】基础画像；【用法】表单选择；【示例】1=男；【参数】枚举；【返回值】int', verbose_name='性别')),
                ('age', models.PositiveIntegerField(blank=True, help_text='【业务说明】评估依从性风险；【用法】可空；【示例】55；【参数】int；【返回值】int', null=True, verbose_name='年龄')),
                ('id_card', models.CharField(blank=True, help_text='【业务说明】VIP 服务需要实名；【用法】销售录入；【示例】310************123；【参数】str；【返回值】str', max_length=18, verbose_name='身份证号')),
                ('source', models.PositiveSmallIntegerField(choices=[(1, '线下销售建档'), (2, '线上自注册')], default=1, help_text='【业务说明】区分线下/线上来源；【用法】统计渠道占比；【示例】1=线下；【参数】枚举；【返回值】int', verbose_name='档案来源')),
                ('claim_status', models.PositiveSmallIntegerField(choices=[(0, '待认领'), (1, '已认领')], default=1, help_text='【业务说明】标识档案是否有人管理；【用法】认领流程更新；【示例】0=待认领；【参数】枚举；【返回值】int', verbose_name='认领状态')),
                ('service_status', models.PositiveSmallIntegerField(choices=[(1, '免费/游客'), (2, '付费会员'), (3, '已过期')], default=1, help_text='【业务说明】冗余会员态；【用法】结合订单定时刷新；【示例】2=会员；【参数】枚举；【返回值】int', verbose_name='服务等级')),
                ('membership_expire_at', models.DateTimeField(blank=True, help_text='【业务说明】会员到期时间；【用法】提醒续费；【示例】2025-05-01 00:00；【参数】datetime；【返回值】datetime', null=True, verbose_name='会员到期时间')),
                ('last_active_at', models.DateTimeField(blank=True, help_text='【业务说明】判断流失；【用法】ETL 更新；【示例】2025-01-10；【参数】datetime；【返回值】datetime', null=True, verbose_name='最后活跃时间')),
                ('device_sn', models.CharField(blank=True, help_text='【业务说明】绑定硬件 SN；【用法】体征自动同步；【示例】POX-2024-8899；【参数】str；【返回值】str', max_length=50, verbose_name='设备 SN')),
                ('ec_name', models.CharField(blank=True, help_text='【业务说明】紧急联系人姓名；【用法】高危预警联系；【示例】张先生；【参数】str；【返回值】str', max_length=50, verbose_name='紧急联系人姓名')),
                ('ec_phone', models.CharField(blank=True, help_text='【业务说明】紧急联系人电话；【用法】一键呼叫；【示例】13900000000；【参数】str；【返回值】str', max_length=20, verbose_name='紧急联系人电话')),
                ('is_active', models.BooleanField(default=True, help_text='【业务说明】软删除/停用控制；【用法】注销档案时置 False；【示例】True；【参数】bool；【返回值】bool', verbose_name='是否有效')),
                ('doctor', models.ForeignKey(blank=True, help_text='【业务说明】主责医生；【用法】销售或运营指定；【示例】DoctorProfile#5；【参数】外键；【返回值】DoctorProfile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='users.doctorprofile', verbose_name='主治医生')),
                ('user', models.OneToOneField(blank=True, help_text='【业务说明】患者本人账号；【用法】自注册或认领后绑定；【示例】CustomUser#12；【参数】外键；【返回值】CustomUser', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='本人账号')),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
            },
        ),
        migrations.CreateModel(
            name='PatientRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime', verbose_name='更新时间')),
                ('relation_type', models.PositiveSmallIntegerField(choices=[(1, '本人'), (2, '父母'), (3, '子女'), (4, '配偶'), (5, '其它')], default=1, help_text='【业务说明】关系类型；【用法】用于展示与权限策略；【示例】3=子女；【参数】枚举；【返回值】int', verbose_name='关系类型')),
                ('relation_name', models.CharField(blank=True, help_text='【业务说明】自定义关系说明；【用法】前端展示例如“女儿”；【示例】女儿；【参数】str；【返回值】str', max_length=20, verbose_name='关系备注')),
                ('is_primary', models.BooleanField(default=False, help_text='【业务说明】是否第一监护人；【用法】决定高危通知优先级；【示例】True；【参数】bool；【返回值】bool', verbose_name='是否第一监护人')),
                ('receive_alert_msg', models.BooleanField(default=False, help_text='【业务说明】是否接收模板消息；【用法】用户自行勾选；【示例】False；【参数】bool；【返回值】bool', verbose_name='是否接收报警')),
                ('patient', models.ForeignKey(help_text='【业务说明】被管理的患者档案；【用法】必填；【示例】PatientProfile#5；【参数】外键；【返回值】PatientProfile', on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='users.patientprofile', verbose_name='患者档案')),
                ('user', models.ForeignKey(help_text='【业务说明】拥有访问权限的账号；【用法】绑定家属；【示例】CustomUser#10；【参数】外键；【返回值】CustomUser', on_delete=django.db.models.deletion.CASCADE, related_name='patient_relations', to=settings.AUTH_USER_MODEL, verbose_name='授权账号')),
            ],
            options={
                'verbose_name': 'Patient Relation',
                'verbose_name_plural': 'Patient Relations',
            },
        ),
        migrations.CreateModel(
            name='SalesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime', verbose_name='更新时间')),
                ('name', models.CharField(help_text='【业务说明】销售真实姓名；【用法】对外展示；【示例】李业务；【参数】str；【返回值】str', max_length=50, verbose_name='销售姓名')),
                ('region', models.CharField(blank=True, help_text='【业务说明】负责区域，如华东；【用法】用于统计；【示例】华东大区；【参数】str；【返回值】str', max_length=100, verbose_name='负责区域')),
                ('invite_code', models.CharField(blank=True, help_text='【业务说明】专属邀请码，用于医生或患者绑定；【用法】可选；【示例】BD2024AB；【参数】str；【返回值】str', max_length=20, null=True, unique=True, verbose_name='专属邀请码')),
                ('managed_doctor_count', models.PositiveIntegerField(default=0, help_text='【业务说明】冗余统计字段，表示目前维护的医生数；【用法】通过定时任务刷新；【示例】5；【参数】int；【返回值】int', verbose_name='医生数量')),
                ('managed_patient_count', models.PositiveIntegerField(default=0, help_text='【业务说明】冗余统计字段，表示名下患者数；【用法】报表展示；【示例】120；【参数】int；【返回值】int', verbose_name='患者数量')),
                ('user', models.OneToOneField(help_text='【业务说明】关联基础账号；【用法】user_type 必须为销售；【示例】CustomUser#20；【参数】外键；【返回值】CustomUser', on_delete=django.db.models.deletion.CASCADE, related_name='sales_profile', to=settings.AUTH_USER_MODEL, verbose_name='销售账号')),
            ],
            options={
                'verbose_name': 'Sales Profile',
                'verbose_name_plural': 'Sales Profiles',
            },
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sales',
            field=models.ForeignKey(blank=True, help_text='【业务说明】负责该患者的销售；【用法】销售建档绑定；【示例】SalesProfile#3；【参数】外键；【返回值】SalesProfile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='users.salesprofile', verbose_name='归属销售'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='sales',
            field=models.ForeignKey(blank=True, help_text='【业务说明】负责维护该医生的销售；【用法】绩效归属；【示例】SalesProfile#2；【参数】外键；【返回值】SalesProfile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='users.salesprofile', verbose_name='负责销售'),
        ),
        migrations.AddConstraint(
            model_name='doctorassistantmap',
            constraint=models.UniqueConstraint(fields=('doctor', 'assistant'), name='uq_doctor_assistant_pair'),
        ),
        migrations.AddConstraint(
            model_name='patientrelation',
            constraint=models.UniqueConstraint(fields=('patient', 'user'), name='uq_patient_user_relation'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['doctor'], name='users_patie_doctor__bcd4ec_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['phone'], name='users_patie_phone_fe1f73_idx'),
        ),
    ]
