# Generated by Django 5.2.8 on 2025-11-25 12:28

import users.models.custom_user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_doctorprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAdminUser',
            fields=[
            ],
            options={
                'verbose_name': '平台管理员',
                'verbose_name_plural': '平台管理员',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
            managers=[
                ('objects', users.models.custom_user.PlatformAdminUserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='assistantprofile',
            options={'verbose_name': '医生助理', 'verbose_name_plural': '医生助理'},
        ),
        migrations.AlterModelOptions(
            name='doctorstudio',
            options={'verbose_name': '医生工作室', 'verbose_name_plural': '医生工作室'},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': '患者列表', 'verbose_name_plural': '患者列表'},
        ),
        migrations.RemoveField(
            model_name='doctorstudio',
            name='qr_code_url',
        ),
    ]
