# Generated by Django 5.2.8 on 2025-11-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_platformadminuser_alter_assistantprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.CharField(blank=True, help_text='【业务说明】患者联系地址；【用法】邮寄资料或上门；【示例】上海市浦东新区XX路；【参数】str；【返回值】str', max_length=100, verbose_name='联系地址'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='【业务说明】用于推算年龄、评估依从风险；【用法】可空；【示例】1969-05-10；【参数】date；【返回值】date', null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='ec_relation',
            field=models.CharField(blank=True, help_text='【业务说明】如父子/配偶；【用法】便于识别联系人；【示例】父子；【参数】str；【返回值】str', max_length=20, verbose_name='紧急联系人关系'),
        ),
    ]
