# Generated by Django 5.2.8 on 2025-11-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_patientprofile_qrcode_expire_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrelation',
            name='is_primary',
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='service_status',
            field=models.PositiveSmallIntegerField(choices=[(1, '免费'), (2, '付费会员'), (3, '已过期')], default=1, help_text='【业务说明】冗余会员态；【用法】结合订单定时刷新；【示例】2=会员；【参数】枚举；【返回值】int', verbose_name='服务等级'),
        ),
        migrations.AlterField(
            model_name='patientrelation',
            name='receive_alert_msg',
            field=models.BooleanField(default=False, help_text='【业务说明】是否接收模板消息；【用法】用户自行勾选；【示例】False；【参数】bool；【返回值】bool', verbose_name='是否接收通知'),
        ),
    ]
