# Generated by Django 5.2.8 on 2025-11-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_salesprofile_qrcode_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrelation",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="【业务说明】软删除标记；【用法】解绑时置为 False；【示例】True；【参数】bool；【返回值】bool",
                verbose_name="是否有效",
            ),
        ),
    ]
