# Generated by Django 5.2.8 on 2025-12-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_patientprofile_monitoring_baselines'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrelation',
            name='phone',
            field=models.CharField(blank=True, help_text='【业务说明】家属的手机号；【用法】可选填写；【示例】13800138000；【参数】str；【返回值】str', max_length=15, null=True, verbose_name='手机号'),
        ),
    ]
