# Generated by Django 5.2.8 on 2025-12-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_patientrelation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrelation',
            name='name',
            field=models.CharField(blank=True, help_text='【业务说明】家属的真实姓名；【用法】可选填写；【示例】张三；【参数】str；【返回值】str', max_length=50, verbose_name='家属姓名'),
        ),
    ]
