# Generated by Django 5.2.8 on 2025-12-20 00:00

from django.core.validators import MaxLengthValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_patientrelation_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="remark",
            field=models.TextField(
                blank=True,
                help_text="【业务说明】患者备注信息（最多500字）；【用法】医生或销售补充；【示例】需重点关注；【参数】str；【返回值】str",
                validators=[MaxLengthValidator(500)],
                verbose_name="备注",
            ),
        ),
    ]
