# Generated by Django 5.2.8 on 2026-02-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_patientprofile_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_receive_wechat_message",
            field=models.BooleanField(
                default=True,
                help_text="【业务说明】用户开关：是否接收公众号/微信推送消息；【用法】提醒设置页可配置；【示例】True；【参数】bool；【返回值】bool",
                verbose_name="是否接收公众号消息",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_receive_watch_message",
            field=models.BooleanField(
                default=True,
                help_text="【业务说明】用户开关：是否接收手表推送消息；【用法】提醒设置页可配置；【示例】True；【参数】bool；【返回值】bool",
                verbose_name="是否接收手表消息",
            ),
        ),
    ]

