# Generated by Django 5.2.8 on 2026-01-31 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_patientprofile_remark"),
        ("wx", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SendMessageLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, help_text="【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime", verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, help_text="【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime", verbose_name="更新时间")),
                ("openid", models.CharField(blank=True, db_index=True, help_text="发送时使用的 OpenID 快照。", max_length=64, verbose_name="OpenID")),
                ("scene", models.CharField(choices=[("daily_task_created", "每日任务生成"), ("daily_task_reminder", "每日任务提醒")], db_index=True, max_length=50, verbose_name="消息场景")),
                ("biz_date", models.DateField(blank=True, db_index=True, help_text="关联的业务日期，例如任务日期。", null=True, verbose_name="业务日期")),
                ("content", models.TextField(verbose_name="消息内容")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="发送载荷")),
                ("is_success", models.BooleanField(default=True, verbose_name="是否成功")),
                ("error_message", models.CharField(blank=True, max_length=255, verbose_name="错误信息")),
                ("patient", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wx_message_logs", to="users.patientprofile", verbose_name="患者")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wx_message_logs", to="users.customuser", verbose_name="接收用户")),
            ],
            options={
                "verbose_name": "微信消息发送日志",
                "verbose_name_plural": "微信消息发送日志",
                "db_table": "wx_send_message_logs",
                "indexes": [
                    models.Index(fields=["scene", "biz_date"], name="idx_wx_msg_scene_date"),
                    models.Index(fields=["patient", "biz_date"], name="idx_wx_msg_patient_date"),
                ],
            },
        ),
    ]
