# Generated by Django 5.2.8 on 2026-01-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wx", "0002_send_message_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendmessagelog",
            name="channel",
            field=models.CharField(choices=[("wechat", "微信"), ("watch", "手表")], db_index=True, default="wechat", max_length=20, verbose_name="发送渠道"),
        ),
    ]
