# Generated by Django 5.2.8 on 2026-03-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wx", "0003_send_message_log_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendmessagelog",
            name="scene",
            field=models.CharField(
                choices=[
                    ("daily_task_created", "每日任务生成"),
                    ("daily_task_reminder", "每日任务提醒"),
                    ("chat_unread", "聊天未读提醒"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="消息场景",
            ),
        ),
    ]
