# Generated by Django 5.2.8 on 2025-11-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='【说明】药物通用名，例如“奥希替尼”；【约束】唯一。', max_length=50, unique=True, verbose_name='通用名')),
                ('trade_names', models.CharField(blank=True, help_text='【说明】常见商品名，可录入多个，以空格或顿号分隔，例如“泰瑞沙”；【约束】可空。', max_length=100, verbose_name='商品名')),
                ('name_abbr', models.CharField(blank=True, help_text='【说明】通用名拼音首字母缩写，例如“奥希替尼”→“AXTN”；【用法】留空时保存会自动生成。', max_length=50, verbose_name='通用名拼音简码')),
                ('trade_names_abbr', models.CharField(blank=True, help_text='【说明】商品名拼音首字母缩写，例如“泰瑞沙”→“TRS”；【用法】留空时保存会自动生成。', max_length=50, verbose_name='商品名拼音简码')),
                ('drug_type', models.PositiveSmallIntegerField(choices=[(1, '靶向治疗'), (2, '化疗'), (3, '免疫治疗'), (4, '抗血管'), (9, '其它')], default=1, help_text='【说明】靶向/化疗/免疫/抗血管/其它。', verbose_name='药物类型')),
                ('method', models.PositiveSmallIntegerField(choices=[(1, '口服'), (2, '静脉'), (9, '其它')], default=1, help_text='【说明】口服/静脉/其它。', verbose_name='给药方式')),
                ('target_gene', models.CharField(blank=True, help_text='【说明】主要靶点，例如 EGFR、ALK；【约束】可空。', max_length=50, verbose_name='靶点')),
                ('default_dosage', models.CharField(blank=True, help_text='【说明】推荐剂量描述，例如“80mg”；【约束】仅作展示。', max_length=50, verbose_name='默认剂量')),
                ('default_frequency', models.CharField(blank=True, help_text='【说明】推荐给药频次，例如“每日 1 次”。', max_length=50, verbose_name='默认频次')),
                ('default_cycle', models.CharField(blank=True, help_text='【说明】给药周期描述，例如“21 天/周期”。', max_length=50, verbose_name='默认周期')),
                ('description', models.TextField(blank=True, help_text='【说明】补充说明、注意事项等。', verbose_name='备注说明')),
                ('is_active', models.BooleanField(default=True, help_text='【说明】控制药物是否可在前台选择。', verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '药物知识库',
                'verbose_name_plural': '药物知识库',
                'db_table': 'core_medication',
            },
        ),
    ]
