# Generated by Django 5.2.8 on 2025-12-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_system_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='current_patient',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedbackimage',
            name='feedback',
        ),
        migrations.DeleteModel(
            name='SystemDocument',
        ),
        migrations.AlterField(
            model_name='medication',
            name='drug_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '靶向治疗'), (2, '化疗'), (3, '免疫治疗'), (4, '合并用药'), (9, '其它')], default=1, help_text='【说明】靶向/化疗/免疫/抗血管/其它。', verbose_name='药物类型'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(1, '口服'), (2, '静脉注射'), (9, '其它')], default=1, help_text='【说明】口服/静脉/其它。', verbose_name='给药方式'),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='FeedbackImage',
        ),
    ]
