# Generated by Django 5.2.8 on 2025-12-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_default_cycle_medication_schedule_days_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='task_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '用药'), (2, '检查'), (3, '随访'), (4, '监测')], verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, '用药'), (2, '检查'), (3, '随访'), (4, '监测')], verbose_name='类型'),
        ),
    ]
