# Generated by Django 5.2.8 on 2025-12-18 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_dailytask_task_type_alter_planitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='问卷名称')),
                ('code', models.CharField(help_text='唯一英文编码，例如 Q_PAIN、Q_SLEEP。', max_length=50, unique=True, verbose_name='问卷编码')),
                ('metric_type', models.CharField(blank=True, help_text='对应 HealthMetric.MetricType，用于将问卷结果存入指标表。', max_length=50, null=True, verbose_name='关联指标类型')),
                ('calculation_strategy', models.CharField(default='SUM', help_text='SUM: 简单累加; AVG: 平均分; CUSTOM_*: 特殊算法', max_length=50, verbose_name='计分策略')),
                ('schedule_days_template', models.JSONField(blank=True, default=list, help_text='周期内执行的 DayIndex 集合，例如 [7, 14, 21]。', verbose_name='推荐执行天(周期内)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序权重')),
            ],
            options={
                'verbose_name': '问卷模板',
                'verbose_name_plural': '问卷模板',
                'db_table': 'core_questionnaires',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.RemoveField(
            model_name='planitem',
            name='followup',
        ),
        migrations.AddField(
            model_name='planitem',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='core.questionnaire', verbose_name='问卷模板'),
        ),
        migrations.CreateModel(
            name='QuestionnaireQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, help_text="问卷内的分组标题，例如'第一部分：基本信息'。", max_length=100, verbose_name='所属章节')),
                ('text', models.TextField(verbose_name='题目内容')),
                ('q_type', models.CharField(choices=[('SINGLE', '单选题'), ('MULTIPLE', '多选题'), ('TEXT', '问答/填空')], default='SINGLE', max_length=20, verbose_name='题目类型')),
                ('seq', models.PositiveIntegerField(default=0, verbose_name='排序号')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='题目分值权重', max_digits=5, verbose_name='权重')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.questionnaire', verbose_name='所属问卷')),
            ],
            options={
                'verbose_name': '问卷题目',
                'verbose_name_plural': '问卷题目',
                'db_table': 'core_questionnaire_questions',
                'ordering': ('seq',),
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='选项内容')),
                ('value', models.CharField(blank=True, help_text='用于代码逻辑的标识值', max_length=50, verbose_name='选项值')),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='该选项对应的得分', max_digits=8, verbose_name='分值')),
                ('seq', models.PositiveIntegerField(default=0, verbose_name='排序号')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.questionnairequestion', verbose_name='所属题目')),
            ],
            options={
                'verbose_name': '题目选项',
                'verbose_name_plural': '题目选项',
                'db_table': 'core_questionnaire_options',
                'ordering': ('seq',),
            },
        ),
        migrations.DeleteModel(
            name='FollowupLibrary',
        ),
    ]
