# Generated by Django 5.2.8 on 2025-12-18 06:45

from django.db import migrations

def seed_questionnaires(apps, schema_editor):
    Questionnaire = apps.get_model("core", "Questionnaire")
    QuestionnaireQuestion = apps.get_model("core", "QuestionnaireQuestion")
    QuestionnaireOption = apps.get_model("core", "QuestionnaireOption")

    # 定义问卷数据结构
    # metric_type: 对应 HealthMetric.MetricType 的值。
    #              如果是复合问卷或不需要自动落库到单一指标，设为 None。
    data = [
        # 1. 睡眠质量 (单指标 -> sleep_quality)
        {
            "name": "睡眠质量评估 (PROMIS-SD 简版)",
            "code": "Q_SLEEP",
            "metric_type": "sleep_quality",
            "questions": [
                {
                    "text": "您最近的睡眠质量是...",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "非常差", "score": 5},
                        {"text": "差", "score": 4},
                        {"text": "一般", "score": 3},
                        {"text": "好", "score": 2},
                        {"text": "非常好", "score": 1},
                    ]
                },
                {
                    "text": "睡眠令人恢复精神。",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "完全没有", "score": 5},
                        {"text": "一点点", "score": 4},
                        {"text": "有些", "score": 3},
                        {"text": "相当多", "score": 2},
                        {"text": "非常", "score": 1},
                    ]
                },
                {
                    "text": "有睡眠问题。",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "完全没有", "score": 1},
                        {"text": "一点点", "score": 2},
                        {"text": "有些", "score": 3},
                        {"text": "相当多", "score": 4},
                        {"text": "非常", "score": 5},
                    ]
                },
                {
                    "text": "难以入睡。",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "完全没有", "score": 1},
                        {"text": "一点点", "score": 2},
                        {"text": "有些", "score": 3},
                        {"text": "相当多", "score": 4},
                        {"text": "非常", "score": 5},
                    ]
                },
                {
                    "text": "睡眠不安稳。",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "完全没有", "score": 1},
                        {"text": "一点点", "score": 2},
                        {"text": "有些", "score": 3},
                        {"text": "相当多", "score": 4},
                        {"text": "非常", "score": 5},
                    ]
                },
                {
                    "text": "努力尝试入睡。",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "完全没有", "score": 1},
                        {"text": "一点点", "score": 2},
                        {"text": "有些", "score": 3},
                        {"text": "相当多", "score": 4},
                        {"text": "非常", "score": 5},
                    ]
                },
                {
                    "text": "担心无法入睡。",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "完全没有", "score": 1},
                        {"text": "一点点", "score": 2},
                        {"text": "有些", "score": 3},
                        {"text": "相当多", "score": 4},
                        {"text": "非常", "score": 5},
                    ]
                },
                {
                    "text": "对睡眠感到满意。",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "完全没有", "score": 5},
                        {"text": "一点点", "score": 4},
                        {"text": "有些", "score": 3},
                        {"text": "相当多", "score": 2},
                        {"text": "非常", "score": 1},
                    ]
                }
            ]
        },
        # 2. 食欲与营养风险评估 (复合 -> 暂不自动映射)
        # 风险等级:
        #   0-3分: 低风险(正常) - 居家康复理想状态
        #   4-8分: 中风险(1级报警) - 轻度厌食/营养不良风险
        #   >=9分: 高风险(2级报警) - 严重营养不良/恶液质风险
        {
            "name": "食欲与营养风险评估",
            "code": "Q_APPETITE",
            "metric_type": None,
            "questions": [
                {
                    "text": "与平时（患病前）相比，您现在的进食量大约是多少？",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "进食正常或比平时多", "score": 0},
                        {"text": "约为平时的 70%-90%", "score": 1},
                        {"text": "约为平时的 50%-60%", "score": 2},
                        {"text": "少于平时的 50% 或几乎不吃", "score": 4},
                    ]
                },
                {
                    "text": "最近 1 个月内，您的体重是否有下降？",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "无下降或体重增加", "score": 0},
                        {"text": "下降约 1-3 kg", "score": 1},
                        {"text": "下降 > 3 kg", "score": 3},
                        {"text": "不清楚，但衣服明显变松", "score": 2},
                    ]
                },
                {
                    "text": "请为您的食欲打分，0分表示“完全没有食欲/看见食物就恶心”，10分表示“食欲极好/很想吃东西”",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "8-10分", "score": 0},
                        {"text": "5-7分", "score": 1},
                        {"text": "3-4分", "score": 2},
                        {"text": "0-2分", "score": 3},
                    ]
                },
                {
                    "text": "是否存在以下影响进食的症状？（多选）",
                    "q_type": "MULTIPLE",
                    "options": [
                        {"text": "恶心/呕吐", "score": 1},
                        {"text": "吞咽困难/吞咽痛", "score": 1},
                        {"text": "口腔溃疡/口干", "score": 1},
                        {"text": "嗅觉或味觉改变（觉得食物有苦味/金属味）", "score": 1},
                        {"text": "呼吸急促/气短（吃几口就喘）", "score": 1},
                        {"text": "便秘或腹泻", "score": 1},
                        {"text": "疼痛（胸痛或全身痛）", "score": 1},
                        {"text": "易饱感（吃两口就饱了）", "score": 1},
                    ]
                },
                {
                    "text": "您最近的活动能力如何？",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "活动自如，能进行日常散步等活动", "score": 0},
                        {"text": "容易疲劳，多数时间需要坐着或躺着，但能下地", "score": 1},
                        {"text": "超过一半时间必须卧床", "score": 3},
                    ]
                }
            ]
        },
        # 3. 心理痛苦分级评估 (DT + PHQ-9 + GAD-7)
        # 结构复杂，包含4个部分，风险计算需独立逻辑，故 metric_type=None
        {
            "name": "心理痛苦分级评估",
            "code": "Q_PSYCH",
            "metric_type": None,
            "questions": [
                # --- 第一部分：DT (痛苦温度计) ---
                {
                    "section": "第一部分：痛苦温度计 (DT)",
                    "text": "请圈出您过去一周内的心理痛苦程度（0分无痛苦，10分极度痛苦）",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": f"{i}分", "score": i} for i in range(11)
                    ]
                },
                # --- 第二部分：PHQ-9 (抑郁) ---
                # 选项通用配置
                # 0: 完全不会, 1: 好几天, 2: 一半以上天数, 3: 几乎每天
            ] + [
                {
                    "section": "第二部分：近期您生活中出现以下症状的频率有多少？",
                    "text": text,
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "完全不会", "score": 0},
                        {"text": "好几天", "score": 1},
                        {"text": "一半以上天数", "score": 2},
                        {"text": "几乎每天", "score": 3},
                    ]
                } for text in [
                    "做事提不起劲或没有兴趣",
                    "感到心情低落、沮丧或绝望",
                    "入睡困难、睡不安稳或睡眠过多",
                    "感到疲倦或没有活力",
                    "食欲不振或吃太多",
                    "觉得自己很糟或觉得自己很失败，让自己或家人失望",
                    "对事物专注有困难（如看报纸或看电视时）",
                    "动作或说话速度缓慢；或者相反，烦躁坐立不安",
                    "有不如死掉或用某种方式伤害自己的念头",
                ]
            ] + [
                # --- 第三部分：GAD-7 (焦虑) ---
                {
                    "section": "第三部分：近期您生活中出现以下症状的频率有多少？",
                    "text": text,
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "完全不会", "score": 0},
                        {"text": "好几天", "score": 1},
                        {"text": "一半以上天数", "score": 2},
                        {"text": "几乎每天", "score": 3},
                    ]
                } for text in [
                    "感觉神经质、焦虑或急切",
                    "不能停止或无法控制担忧",
                    "对各种各样的事情担忧过多",
                    "很难放松下来（常伴随呼吸急促感）",
                    "由于不安而无法静坐",
                    "变得容易烦恼或急躁",
                    "感到似乎将有可怕的事情发生",
                ]
            ] + [
                # --- 第四部分：痛苦原因 (多选，不计分) ---
                {
                    "section": "第四部分：如果您感到痛苦或情绪不佳，主要原因是什么？（多选）",
                    "text": "躯体症状（如果您感到痛苦，主要原因包含哪些？）",
                    "q_type": "MULTIPLE",
                    "options": [
                        {"text": "呼吸困难/气短", "score": 0},
                        {"text": "疼痛", "score": 0},
                        {"text": "咳嗽/咳痰", "score": 0},
                        {"text": "乏力", "score": 0},
                        {"text": "睡眠问题", "score": 0},
                    ]
                },
                {
                    "section": "第四部分：如果您感到痛苦或情绪不佳，主要原因是什么？（多选）",
                    "text": "实际问题（如果您感到痛苦，主要原因包含哪些？）",
                    "q_type": "MULTIPLE",
                    "options": [
                        {"text": "经济压力", "score": 0},
                        {"text": "就医/复查不便", "score": 0},
                        {"text": "没有人照顾", "score": 0},
                    ]
                },
                {
                    "section": "第四部分：如果您感到痛苦或情绪不佳，主要原因是什么？（多选）",
                    "text": "疾病认知（如果您感到痛苦，主要原因包含哪些？）",
                    "q_type": "MULTIPLE",
                    "options": [
                        {"text": "担心复发/转移", "score": 0},
                        {"text": "对治疗副作用的恐惧", "score": 0},
                        {"text": "不了解康复知识", "score": 0},
                    ]
                }
            ]
        },
        # 4. 多部位疼痛评估 (复合指标 -> 暂不自动映射单一 metric_type)
        {
            "name": "疼痛评估",
            "code": "Q_PAIN",
            "metric_type": None,
            "questions": [
                {
                    "text": "术口/胸膛/肋间",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "无疼痛", "score": 0},
                        {"text": "轻度", "score": 2},
                        {"text": "中度", "score": 5},
                        {"text": "重度", "score": 9},
                    ]
                },
                {
                    "text": "肩峰/肩背/肩胛",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "无疼痛", "score": 0},
                        {"text": "轻度", "score": 2},
                        {"text": "中度", "score": 5},
                        {"text": "重度", "score": 9},
                    ]
                },
                {
                    "text": "肋骨/脊柱/骨盆/四肢",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "无疼痛", "score": 0},
                        {"text": "轻度", "score": 2},
                        {"text": "中度", "score": 5},
                        {"text": "重度", "score": 9},
                    ]
                },
                {
                    "text": "头部",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "无疼痛", "score": 0},
                        {"text": "轻度", "score": 2},
                        {"text": "中度", "score": 5},
                        {"text": "重度", "score": 9},
                    ]
                },
            ]
        },
        # 5. 咳嗽与痰色 (复合 -> 暂不自动映射，依靠总分报警)
        {
            "name": "咳嗽与痰色情况随访",
            "code": "Q_COUGH",
            "metric_type": None,
            "questions": [
                {
                    "text": "最近的咳嗽情况如何？",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "近期无咳嗽情况。", "score": 0},
                        {"text": "偶尔有点轻微咳嗽，但不影响说话和吃饭，也不用吃药。", "score": 1},
                        {"text": "需要吃止咳药才能压住，或者咳嗽打断聊天、做家务。", "score": 2},
                        {"text": "严重影响睡眠，甚至吃饭、穿衣服都受影响，感觉很痛苦。", "score": 3},
                    ]
                },
                {
                    "text": "最近痰液性状情况如何？",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "无痰，或只是干咳。", "score": 0},
                        {"text": "像唾沫或蛋清一样，不浑浊。", "score": 0},
                        {"text": "痰有点稠，颜色稍微有点黄，但不算很深。", "score": 1},
                        {"text": "像脓一样的深黄色或绿色，很粘稠，甚至是一坨一坨的。", "score": 3},
                    ]
                },
                {
                    "text": "咳嗽或痰中是否带血？",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "完全没血，痰很干净。", "score": 0},
                        {"text": "痰里夹杂着几条红血丝，或者痰带点粉红色。", "score": 3},
                        {"text": "咳出来的全是红色的血，大概有一两口那么多。", "score": 5},
                        {"text": "血量很大，止不住。", "score": 9},
                    ]
                },
                # 以下两题为背景信息，不参与总分计算 (Score=0)
                {
                    "text": "发生以上情况时的体温情况如何？",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "正常，37℃左右。", "score": 0},
                        {"text": "有点低烧 (37.3℃ - 38.0℃)。", "score": 0},
                        {"text": "发高烧 (38.0℃以上，或者感觉身体发冷打寒战)。", "score": 0},
                        {"text": "未测量，不清楚。", "score": 0},
                    ]
                },
                {
                    "text": "发生以上情况时的血氧情况如何？",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "正常，95以上。", "score": 0},
                        {"text": "略低，90-94之间。", "score": 0},
                        {"text": "很低，低于90。", "score": 0},
                        {"text": "未测量，不清楚。", "score": 0},
                    ]
                }
            ]
        },
        # 6. 体能与呼吸困难 (复合 -> 暂不自动映射)
        {
            "name": "体能与呼吸评估",
            "code": "Q_PHYSICAL",
            "metric_type": None,
            "questions": [
                {
                    "text": "请为您目前的疲惫程度打分，0分表示精力充沛，10分表示精疲力竭，完全动不了。",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": f"{i}分", "score": i} for i in range(11)
                    ]
                },
                {
                    "text": "您近期日常活动能力如何？",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "A. 我完全正常，没有任何症状，和生病前一样能进行各种活动（包括跑步、提重物等）。", "score": 0},
                        {"text": "B. 我有轻微症状（如咳嗽、轻微疼痛），不能做剧烈运动，但可以进行轻体力工作（如简单的家务、办公室工作）。", "score": 1},
                        {"text": "C. 我生活能自理（吃饭、穿衣、洗漱），白天能起床走动，但无法进行工作。白天卧床时间少于一半。", "score": 2},
                        {"text": "D. 我生活只能部分自理，大部分时间需要卧床或坐在椅子上。白天卧床时间超过一半。", "score": 3},
                        {"text": "E. 我完全不能自理，需要别人完全照顾，全天卧床或坐在椅子上。", "score": 4},
                    ]
                },
                {
                    "text": "您在活动时感到气短/呼吸困难的程度？",
                    "q_type": "SINGLE",
                    "options": [
                        {"text": "A. 我只在剧烈运动（如快跑、爬高层楼梯）时才感到气喘。", "score": 0},
                        {"text": "B. 我在平地快走或上小斜坡时会感到气喘。", "score": 1},
                        {"text": "C. 我在平地行走时，因为气喘必须比同龄人走得慢，或者按自己节奏走几分钟就得停下来喘口气。", "score": 2},
                        {"text": "D. 我在平地走约 100 米，或才几分钟，就不得不停下来喘口气。", "score": 3},
                        {"text": "E. 我因为气喘太严重而无法离开房间，或者穿脱衣服时都会气喘。", "score": 4},
                    ]
                }
            ]
        }
    ]

    for idx, q_data in enumerate(data):
        # 1. 创建/更新问卷
        questionnaire, _ = Questionnaire.objects.update_or_create(
            code=q_data["code"],
            defaults={
                "name": q_data["name"],
                "metric_type": q_data["metric_type"],
                "sort_order": idx + 1,
                "is_active": True,
                "calculation_strategy": "SUM", # 默认累加策略
            }
        )

        # 2. 创建/更新题目
        # 注意：这里简化处理，如果题目数量变动较大，建议先清空该问卷的题目
        # 但为了保留已有数据的引用，这里采用 update_or_create
        for q_idx, question_data in enumerate(q_data["questions"]):
            question, _ = QuestionnaireQuestion.objects.update_or_create(
                questionnaire=questionnaire,
                text=question_data["text"], # 以题目内容为 key 可能会有问题，但在初始化脚本中通常可行
                defaults={
                    "section": question_data.get("section", ""),
                    "q_type": question_data.get("q_type", "SINGLE"),
                    "seq": q_idx + 1,
                    "is_required": question_data.get("is_required", True),
                }
            )

            # 3. 创建选项
            # 选项变动较多，且 ID 不敏感，先清空再重建比较稳妥
            question.options.all().delete()
            
            options_to_create = []
            for opt_idx, opt_data in enumerate(question_data["options"]):
                options_to_create.append(
                    QuestionnaireOption(
                        question=question,
                        text=opt_data["text"],
                        score=opt_data["score"],
                        seq=opt_idx + 1,
                        value=str(opt_data["score"])
                    )
                )
            QuestionnaireOption.objects.bulk_create(options_to_create)

def reverse_seed(apps, schema_editor):
    # 回滚操作：可选择删除这些数据，或者留空
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_questionnaire_remove_planitem_followup_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_questionnaires, reverse_seed),
    ]