# Generated by Django 5.2.8 on 2025-12-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seed_initial_questionnaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='task_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '用药'), (2, '检查'), (3, '问卷'), (4, '监测')], verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, '用药'), (2, '检查'), (3, '问卷'), (4, '监测')], verbose_name='类型'),
        ),
    ]
