# Generated by Django 5.2.8 on 2025-12-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delete_monitoringconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringtemplate',
            name='schedule_days_template',
            field=models.JSONField(blank=True, default=list, help_text='周期内执行的 DayIndex 集合，例如 [1,3,5,7] 表示每2天一次。', verbose_name='推荐执行天(周期内)'),
        ),
    ]
