# Generated by Django 5.2.8 on 2025-12-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_planitem_interaction_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='interaction_payload',
            field=models.JSONField(blank=True, default=dict, help_text='生成任务时保留的交互配置快照。', verbose_name='交互配置快照'),
        ),
    ]
