# Generated by Django 5.2.8 on 2025-12-21 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_dailytask_interaction_payload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planitem',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_plan_items',
                to=settings.AUTH_USER_MODEL,
                verbose_name='创建人',
            ),
        ),
        migrations.AddField(
            model_name='planitem',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='updated_plan_items',
                to=settings.AUTH_USER_MODEL,
                verbose_name='更新人',
            ),
        ),
        migrations.AddField(
            model_name='planitem',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='创建时间',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planitem',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                verbose_name='更新时间',
            ),
            preserve_default=False,
        ),
    ]
