# Generated by Django 5.2.8 on 2025-12-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_planitem_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未做'), (1, '已完成')], default=0, verbose_name='完成状态'),
        ),
    ]
