# Generated by Django 5.2.8 on 2026-01-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_questionnaire_metric_type_and_reseed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailytask",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "未完成"), (1, "已完成"), (2, "未开始"), (3, "已终止")],
                default=0,
                verbose_name="完成状态",
            ),
        ),
    ]
