# Generated by Django 5.2.8 on 2026-02-08 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_dailytask_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailytask",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailytask",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                verbose_name="更新时间",
            ),
            preserve_default=False,
        ),
    ]
