# Generated by Django 5.2.8 on 2026-04-02

import django.db.models.deletion
from django.db import migrations, models


def seed_standard_fields(apps, schema_editor):
    CheckupLibrary = apps.get_model("core", "CheckupLibrary")
    StandardField = apps.get_model("core", "StandardField")
    StandardFieldAlias = apps.get_model("core", "StandardFieldAlias")
    CheckupFieldMapping = apps.get_model("core", "CheckupFieldMapping")

    from core.service.standard_field_seed import sync_standard_field_seed

    sync_standard_field_seed(
        standard_field_model=StandardField,
        alias_model=StandardFieldAlias,
        mapping_model=CheckupFieldMapping,
        checkup_model=CheckupLibrary,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_dailytask_audit_timestamps"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("local_code", models.CharField(help_text="系统内部稳定编码，例如 WBC、ALT、IMG_FINDINGS。", max_length=64, unique=True, verbose_name="本地标准编码")),
                ("english_abbr", models.CharField(blank=True, help_text="字段简称，例如 WBC、ALT；可为空。", max_length=64, verbose_name="英文简称")),
                ("chinese_name", models.CharField(help_text="用于后台展示的规范中文名称。", max_length=100, verbose_name="中文标准名")),
                ("value_type", models.CharField(choices=[("DECIMAL", "数值"), ("TEXT", "文本")], default="DECIMAL", help_text="结果值存储方式，仅支持数值或文本。", max_length=16, verbose_name="值类型")),
                ("default_unit", models.CharField(blank=True, help_text="默认展示单位，例如 g/L、10^9/L；文本字段可留空。", max_length=50, verbose_name="默认单位")),
                ("description", models.TextField(blank=True, help_text="补充该字段的业务含义或使用说明。", verbose_name="字段说明")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序权重")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "标准字段",
                "verbose_name_plural": "标准字段",
                "db_table": "core_standard_fields",
                "ordering": ("sort_order", "local_code"),
            },
        ),
        migrations.CreateModel(
            name="StandardFieldAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("alias_name", models.CharField(help_text="OCR/AI 可能识别出的原始名称。", max_length=100, verbose_name="别名原文")),
                ("normalized_name", models.CharField(db_index=True, editable=False, help_text="系统自动生成，用于唯一匹配。", max_length=100, unique=True, verbose_name="归一化名称")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("notes", models.TextField(blank=True, help_text="记录该别名来源医院或特殊说明。", verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("standard_field", models.ForeignKey(help_text="别名最终指向的标准字段。", on_delete=django.db.models.deletion.CASCADE, related_name="aliases", to="core.standardfield", verbose_name="所属标准字段")),
            ],
            options={
                "verbose_name": "标准字段别名",
                "verbose_name_plural": "标准字段别名",
                "db_table": "core_standard_field_aliases",
                "ordering": ("alias_name", "id"),
            },
        ),
        migrations.CreateModel(
            name="CheckupFieldMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="该字段在当前检查项下的展示顺序。", verbose_name="排序权重")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("checkup_item", models.ForeignKey(help_text="允许使用该字段的检查项。", on_delete=django.db.models.deletion.CASCADE, related_name="standard_field_mappings", to="core.checkuplibrary", verbose_name="检查项")),
                ("standard_field", models.ForeignKey(help_text="当前检查项支持的标准字段。", on_delete=django.db.models.deletion.CASCADE, related_name="checkup_mappings", to="core.standardfield", verbose_name="标准字段")),
            ],
            options={
                "verbose_name": "检查项字段映射",
                "verbose_name_plural": "检查项字段映射",
                "db_table": "core_checkup_field_mappings",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="checkupfieldmapping",
            constraint=models.UniqueConstraint(fields=("checkup_item", "standard_field"), name="uniq_checkup_standard_field"),
        ),
        migrations.RunPython(seed_standard_fields, migrations.RunPython.noop),
    ]
