# Generated by Django 5.2.8 on 2026-05-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_standardfield_standardfieldalias_checkupfieldmapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(1, '口服'), (2, '静脉注射'), (3, '皮下注射'), (4, '口吸'), (9, '其它')], default=1, help_text='【说明】口服/静脉注射/皮下注射/口吸/其它。', verbose_name='给药方式'),
        ),
    ]
