"""
Django settings for lung_cancer_care project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)

DJANGO_ENV = os.getenv("DJANGO_ENV", "development").lower()
LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO").upper()
ALLOWED_HOSTS_RAW = os.getenv("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_RAW.split(",") if host.strip()]
if DJANGO_ENV != "production" and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = []

WEB_BASE_URL = os.getenv("WEB_BASE_URL", "http://localhost:8001").rstrip("/")
TEST_PATIENT_ID = os.getenv("TEST_PATIENT_ID") or None

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$idrzn%uju_mymafcg9h76u&bq!*2uhs2-yk-!(9i#!+e5x*3='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = DJANGO_ENV != "production"


# Application definition

INSTALLED_APPS = [
    'lung_cancer_care.admin_site.LungCancerAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'users',
    'web_doctor',
    'web_sales',
    'web_patient',
    'market',
    'wx',
    'health_data',
    'regions',
    'business_support',
    'core',
    'patient_alerts',
    'chat',
]

ADMIN_APP_ORDER = [
    'core',
    'users',
    'web_doctor',
    'web_patient',
    'market',
    'web_sales',
    'health_data',
    'business_support',
    'wx',
    'regions',
    'patient_alerts',
    'chat',
]

LOGOUT_REDIRECT_URL = '/admin/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.PatientContextMiddleware',
    'lung_cancer_care.middleware.RequestLogMiddleware',
    
]

ROOT_URLCONF = 'lung_cancer_care.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lung_cancer_care.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("MYSQL_DATABASE"),
        "USER": os.getenv("MYSQL_USER"),
        "PASSWORD": os.getenv("MYSQL_PASSWORD"),
        "HOST": os.getenv("MYSQL_HOST"),
        "PORT": os.getenv("MYSQL_PORT"),
    }
}

REDIS_HOST = os.getenv("REDIS_HOST", "127.0.0.1")
REDIS_PORT = os.getenv("REDIS_PORT", "6379")
REDIS_DB = os.getenv("REDIS_DB", "0")
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", "")
_redis_auth = f":{REDIS_PASSWORD}@" if REDIS_PASSWORD else ""

CELERY_BROKER_URL = f"redis://{_redis_auth}{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

EMBED_URL = os.getenv("EMBED_URL", "")
EMBED_TOKEN = os.getenv("EMBED_TOKEN", "")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",  # <--- 改成这个
        "LOCATION": f"redis://{_redis_auth}{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


LANGUAGE_CODE = "zh-hans"
TIME_ZONE = "Asia/Shanghai"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

CERTS_DIR = BASE_DIR / 'certs'
# 微信支付 v2 证书配置
WX_APPID = os.getenv("WX_APPID")
WX_PAY_PUB_KEY_PATH = CERTS_DIR / 'wx_v2_certs/pub_key.pem'
WX_PAY_CERT_PATH = CERTS_DIR / 'wx_v2_certs/apiclient_cert.pem'
WX_PAY_KEY_PATH = CERTS_DIR / 'wx_v2_certs/apiclient_key.pem'
WX_MCH_ID = os.getenv("WX_MCH_ID")
WX_MCH_KEY = os.getenv("WX_MCH_KEY")
WX_PAY_NOTIFY_URL = os.getenv("WX_PAY_NOTIFY_URL")


STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.CustomUser'

LOGIN_URL = 'web_doctor:login'
LOGIN_REDIRECT_URL = 'web_doctor:doctor_dashboard'
LOGOUT_REDIRECT_URL = 'web_doctor:login'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "lung_cancer_care.logging_utils.JsonFormatter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
        "file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": LOG_DIR / "lung_cancer_care.log",
            "when": "midnight",
            "interval": 1,
            "backupCount": 20,
            "formatter": "json",
            "encoding": "utf-8", # 建议加上编码
        },
    },
    "root": {  # 新增
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "ERROR",
            "propagate": False,
        },
        "lung_cancer_care": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "lung_cancer_care.request": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        # 【新增】专门打印 SQL 语句的配置
        "django.db.backends": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# 测试环境下禁用控制台日志输出，避免污染测试结果
if 'test' in sys.argv:
    LOGGING['handlers']['console'] = {'class': 'logging.NullHandler'}


#短信配置
SMS_CONFIG = {
    'API_URL': os.environ.get('SMS_API_URL', 'http://124.172.234.157:8180/service.asmx/SendMessageStr'),
    'ORG_ID': os.environ.get('SMS_ORG_ID'),
    'USERNAME': os.environ.get('SMS_USERNAME'),
    'PASSWORD': os.environ.get('SMS_PASSWORD'), 
    'SIGNATURE': '【岱劲信息】', # 建议配置签名，避免被拦截
}

#智能手表配置
SMARTWATCH_CONFIG = {
    'APP_KEY': os.environ.get('SMARTWATCH_APP_KEY'),
    'APP_SECRET': os.environ.get('SMARTWATCH_APP_SECRET'),
    'API_BASE_URL': 'https://apibff.scheartmed.com',  # [cite: 412]
}

"""
初始化数据库
CREATE DATABASE IF NOT EXISTS `lung_cancer_care`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_0900_ai_ci;
"""

# shell_plus
SHELL_PLUS = "ipython"
SHELL_PLUS_IMPORTS = []
SHELL_PLUS_PRINT_SQL = False
_redis_auth = f":{REDIS_PASSWORD}@" if REDIS_PASSWORD else ""
CELERY_BROKER_URL = f"redis://{_redis_auth}{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
