# Generated by Django 5.2.8 on 2026-01-05 09:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_patientprofile_remark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('data', 'Data Anomaly'), ('behavior', 'Behavior Anomaly'), ('archive', 'New Record'), ('questionnaire', 'Questionnaire Anomaly'), ('other', 'Other')], help_text='Category of the alert.', max_length=30, verbose_name='Event type')),
                ('event_level', models.PositiveSmallIntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], help_text='Severity level of the alert.', verbose_name='Event level')),
                ('event_title', models.CharField(help_text='Short title shown in the todo list.', max_length=200, verbose_name='Event title')),
                ('event_content', models.TextField(blank=True, help_text='Detailed description for follow-up.', verbose_name='Event content')),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When the alert was triggered.', verbose_name='Event time')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Escalated'), (3, 'Completed')], default=1, help_text='Follow-up status for this alert.', verbose_name='Status')),
                ('handle_time', models.DateTimeField(blank=True, help_text='When the alert was handled.', null=True, verbose_name='Handled time')),
                ('handle_content', models.TextField(blank=True, help_text='Handling notes or resolution details.', verbose_name='Handle content')),
                ('source_type', models.CharField(blank=True, help_text='Origin type, e.g. metric or questionnaire.', max_length=50, verbose_name='Source type')),
                ('source_id', models.BigIntegerField(blank=True, help_text='Origin record ID.', null=True, verbose_name='Source ID')),
                ('source_payload', models.JSONField(blank=True, default=dict, help_text='Snapshot of source details.', verbose_name='Source payload')),
                ('is_active', models.BooleanField(default=True, help_text='Soft disable flag.', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record update time.', verbose_name='Updated at')),
                ('doctor', models.ForeignKey(blank=True, help_text='Doctor responsible for follow-up.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_alerts', to='users.doctorprofile', verbose_name='Assigned doctor')),
                ('handler', models.ForeignKey(blank=True, help_text='User who handled the alert.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_patient_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Handler')),
                ('patient', models.ForeignKey(help_text='Target patient profile for this alert.', on_delete=django.db.models.deletion.CASCADE, related_name='patient_alerts', to='users.patientprofile', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Patient alert',
                'verbose_name_plural': 'Patient alerts',
                'db_table': 'patient_alerts',
                'ordering': ('-event_time', '-id'),
                'indexes': [models.Index(fields=['patient', 'status'], name='patient_ale_patient_817dee_idx'), models.Index(fields=['doctor', 'status'], name='patient_ale_doctor__ef7eea_idx'), models.Index(fields=['event_type', 'event_level'], name='patient_ale_event_t_5f7472_idx'), models.Index(fields=['event_time'], name='patient_ale_event_t_ea0fcd_idx')],
            },
        ),
    ]
