# Generated by Django 5.2.8 on 2026-03-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientalert",
            name="handle_meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Latest handling snapshot and full handling history.",
                verbose_name="Handle meta",
            ),
        ),
    ]
