# Generated by Codex on 2026-06-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_alerts", "0002_patientalert_handle_meta"),
        ("users", "0020_patientprofile_baseline_height_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientAlertSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_type", models.CharField(help_text="Origin type, e.g. metric, questionnaire, or behavior_medication.", max_length=80, verbose_name="Source type")),
                ("source_id", models.BigIntegerField(blank=True, help_text="Origin record ID when one exists.", null=True, verbose_name="Source ID")),
                ("source_key", models.CharField(help_text="Stable idempotency key for this alert source.", max_length=160, unique=True, verbose_name="Source key")),
                ("source_label", models.CharField(help_text="Human-readable source name shown in alert detail.", max_length=120, verbose_name="Source label")),
                ("value_display", models.CharField(blank=True, help_text="Snapshot of the abnormal value or fact.", max_length=200, verbose_name="Value display")),
                ("baseline_display", models.CharField(blank=True, help_text="Snapshot of the baseline when available.", max_length=200, verbose_name="Baseline display")),
                ("event_level", models.PositiveSmallIntegerField(choices=[(1, "Mild"), (2, "Moderate"), (3, "Severe")], help_text="Severity level of this source record.", verbose_name="Event level")),
                ("occurred_at", models.DateTimeField(help_text="When this source abnormality happened.", verbose_name="Occurred at")),
                ("source_payload", models.JSONField(blank=True, default=dict, help_text="Full source snapshot for detail display and statistics.", verbose_name="Source payload")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Record creation time.", verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Record update time.", verbose_name="Updated at")),
                ("alert", models.ForeignKey(help_text="Aggregated alert this source record belongs to.", on_delete=django.db.models.deletion.CASCADE, related_name="sources", to="patient_alerts.patientalert", verbose_name="Patient alert")),
                ("patient", models.ForeignKey(help_text="Target patient profile for this source record.", on_delete=django.db.models.deletion.CASCADE, related_name="patient_alert_sources", to="users.patientprofile", verbose_name="Patient")),
            ],
            options={
                "verbose_name": "Patient alert source",
                "verbose_name_plural": "Patient alert sources",
                "db_table": "patient_alert_sources",
                "ordering": ("-occurred_at", "-id"),
                "indexes": [
                    models.Index(fields=["alert", "occurred_at"], name="patient_ale_alert_i_aef4d9_idx"),
                    models.Index(fields=["patient", "source_type", "occurred_at"], name="patient_ale_patient_4b15bd_idx"),
                    models.Index(fields=["source_type", "source_id"], name="patient_ale_source__ba8506_idx"),
                ],
            },
        ),
    ]
