# Generated by Django 5.2.8 on 2025-11-27 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_remove_patientrelation_is_primary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime', verbose_name='更新时间')),
                ('name', models.CharField(help_text='【说明】服务包名称；【示例】VIP 监护服务', max_length=100, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, help_text='【说明】标注售价；【示例】199.00', max_digits=10, verbose_name='销售价格')),
                ('duration_days', models.PositiveIntegerField(help_text='【说明】服务有效天数；【示例】30', verbose_name='服务有效期（天）')),
                ('is_active', models.BooleanField(default=True, help_text='【说明】控制商品销售状态；1=上架，0=下架', verbose_name='是否上架')),
            ],
            options={
                'verbose_name': '商品/服务包',
                'verbose_name_plural': '商品/服务包',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime', verbose_name='更新时间')),
                ('order_no', models.CharField(blank=True, help_text='【说明】唯一订单编号，自动生成。', max_length=32, unique=True, verbose_name='订单编号')),
                ('amount', models.DecimalField(decimal_places=2, help_text='【说明】最终支付金额；可包含优惠。', max_digits=10, verbose_name='实际支付金额')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '已取消'), (3, '已退款')], default=1, help_text='【说明】交易状态；默认已支付。', verbose_name='订单状态')),
                ('paid_at', models.DateTimeField(blank=True, help_text='【说明】支付成功时间；默认为当前时间。', null=True, verbose_name='支付时间')),
                ('patient', models.ForeignKey(help_text='【说明】谁购买了该商品。', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.patientprofile', verbose_name='下单患者')),
                ('product', models.ForeignKey(help_text='【说明】购买的服务包。', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='market.product', verbose_name='购买商品')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
