# Generated by Django 5.2.8 on 2026-01-07 07:59

import chat.models.message
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_patientprofile_remark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime', verbose_name='更新时间')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Patient Studio'), (2, 'Internal')], default=1, help_text='Conversation type, patient-facing or internal.', verbose_name='Conversation Type')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Timestamp of the latest message in this conversation.', null=True, verbose_name='Last Message At')),
                ('created_by', models.ForeignKey(blank=True, help_text='Operator who created the conversation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('patient', models.ForeignKey(help_text='Patient profile linked to this conversation.', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='users.patientprofile', verbose_name='Patient')),
                ('studio', models.ForeignKey(help_text='Studio that owns the conversation context.', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='users.doctorstudio', verbose_name='Studio')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime', verbose_name='更新时间')),
                ('sender_role_snapshot', models.PositiveSmallIntegerField(choices=[(1, 'Patient'), (2, 'Family'), (3, 'Director'), (4, 'Platform Doctor'), (5, 'Assistant'), (6, 'CRC'), (99, 'Other')], default=99, help_text='Sender role at the time of sending.', verbose_name='Sender Role Snapshot')),
                ('sender_display_name_snapshot', models.CharField(help_text='Display name captured at send time.', max_length=100, verbose_name='Sender Display Name Snapshot')),
                ('studio_name_snapshot', models.CharField(help_text='Studio name captured at send time.', max_length=100, verbose_name='Studio Name Snapshot')),
                ('content_type', models.PositiveSmallIntegerField(choices=[(1, 'Text'), (2, 'Image')], default=1, help_text='Content type of the message.', verbose_name='Content Type')),
                ('text_content', models.TextField(blank=True, help_text='Text payload for text messages.', verbose_name='Text Content')),
                ('image', models.ImageField(blank=True, help_text='Image file for image messages.', null=True, upload_to=chat.models.message._chat_image_upload_path, verbose_name='Image')),
                ('conversation', models.ForeignKey(help_text='Conversation that this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='Conversation')),
                ('sender', models.ForeignKey(help_text='User who sent this message.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='ConversationReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime', verbose_name='更新时间')),
                ('conversation', models.ForeignKey(help_text='Conversation for this read state.', on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='chat.conversation', verbose_name='Conversation')),
                ('user', models.ForeignKey(help_text='User who owns this read cursor.', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_read_states', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('last_read_message', models.ForeignKey(blank=True, help_text='Latest message that the user has read.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_state_entries', to='chat.message', verbose_name='Last Read Message')),
            ],
            options={
                'verbose_name': 'Conversation Read State',
                'verbose_name_plural': 'Conversation Read States',
            },
        ),
        migrations.CreateModel(
            name='PatientStudioAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime', verbose_name='更新时间')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Assignment start timestamp.', verbose_name='Start At')),
                ('end_at', models.DateTimeField(blank=True, help_text='Assignment end timestamp, null means active.', null=True, verbose_name='End At')),
                ('reason', models.TextField(blank=True, help_text='Optional transfer reason note.', verbose_name='Reason')),
                ('patient', models.ForeignKey(help_text='Patient profile assigned to a studio.', on_delete=django.db.models.deletion.CASCADE, related_name='studio_assignments', to='users.patientprofile', verbose_name='Patient')),
                ('studio', models.ForeignKey(help_text='Studio assigned to the patient.', on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='users.doctorstudio', verbose_name='Studio')),
            ],
            options={
                'verbose_name': 'Patient Studio Assignment',
                'verbose_name_plural': 'Patient Studio Assignments',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['patient', 'type'], name='idx_chat_conv_patient_type'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['studio'], name='idx_chat_conv_studio'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('patient', 'type'), name='uq_chat_conversation_patient_type'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='idx_chat_msg_conv_time'),
        ),
        migrations.AddIndex(
            model_name='conversationreadstate',
            index=models.Index(fields=['conversation', 'user'], name='idx_chat_read_state_conv_user'),
        ),
        migrations.AddConstraint(
            model_name='conversationreadstate',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='uq_chat_read_state_conversation_user'),
        ),
        migrations.AddIndex(
            model_name='patientstudioassignment',
            index=models.Index(fields=['patient', 'end_at'], name='idx_chat_assignment_active'),
        ),
    ]
