# Generated by Django 5.2.8 on 2026-01-10 03:33

import chat.models.message
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("users", "0016_patientprofile_remark"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"verbose_name": "会话", "verbose_name_plural": "会话"},
        ),
        migrations.AlterModelOptions(
            name="conversationreadstate",
            options={
                "verbose_name": "会话已读状态",
                "verbose_name_plural": "会话已读状态",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "消息", "verbose_name_plural": "消息"},
        ),
        migrations.AlterModelOptions(
            name="patientstudioassignment",
            options={
                "verbose_name": "患者工作室归属",
                "verbose_name_plural": "患者工作室归属",
            },
        ),
        migrations.AlterField(
            model_name="conversation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="创建该会话的操作人。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_conversations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="last_message_at",
            field=models.DateTimeField(
                blank=True,
                help_text="该会话最新一条消息的时间。",
                null=True,
                verbose_name="最后消息时间",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="patient",
            field=models.ForeignKey(
                help_text="会话关联的患者档案。",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="users.patientprofile",
                verbose_name="患者",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="studio",
            field=models.ForeignKey(
                help_text="会话所属工作室。",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="users.doctorstudio",
                verbose_name="工作室",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "患者会话"), (2, "内部会话")],
                default=1,
                help_text="会话类型，患者会话或内部会话。",
                verbose_name="会话类型",
            ),
        ),
        migrations.AlterField(
            model_name="conversationreadstate",
            name="conversation",
            field=models.ForeignKey(
                help_text="该已读状态所属的会话。",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_states",
                to="chat.conversation",
                verbose_name="会话",
            ),
        ),
        migrations.AlterField(
            model_name="conversationreadstate",
            name="last_read_message",
            field=models.ForeignKey(
                blank=True,
                help_text="用户已读的最新消息。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="read_state_entries",
                to="chat.message",
                verbose_name="最后已读消息",
            ),
        ),
        migrations.AlterField(
            model_name="conversationreadstate",
            name="user",
            field=models.ForeignKey(
                help_text="拥有该已读游标的用户。",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_read_states",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "文本"), (2, "图片")],
                default=1,
                help_text="消息的内容类型。",
                verbose_name="内容类型",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                help_text="该消息所属的会话。",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.conversation",
                verbose_name="会话",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="图片消息的文件内容。",
                null=True,
                upload_to=chat.models.message._chat_image_upload_path,
                verbose_name="图片",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                help_text="发送该消息的用户。",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发送者",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender_display_name_snapshot",
            field=models.CharField(
                help_text="发送时的展示名称快照。",
                max_length=100,
                verbose_name="发送者展示名快照",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender_role_snapshot",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "患者"),
                    (2, "家属"),
                    (3, "主任"),
                    (4, "平台医生"),
                    (5, "医生助理"),
                    (6, "CRC"),
                    (99, "其他"),
                ],
                default=99,
                help_text="发送时的角色快照。",
                verbose_name="发送者角色快照",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="studio_name_snapshot",
            field=models.CharField(
                help_text="发送时的工作室名称快照。",
                max_length=100,
                verbose_name="工作室名称快照",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="text_content",
            field=models.TextField(
                blank=True, help_text="文本消息的内容。", verbose_name="文本内容"
            ),
        ),
        migrations.AlterField(
            model_name="patientstudioassignment",
            name="end_at",
            field=models.DateTimeField(
                blank=True,
                help_text="归属结束时间，空值表示当前仍有效。",
                null=True,
                verbose_name="结束时间",
            ),
        ),
        migrations.AlterField(
            model_name="patientstudioassignment",
            name="patient",
            field=models.ForeignKey(
                help_text="归属到工作室的患者档案。",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studio_assignments",
                to="users.patientprofile",
                verbose_name="患者",
            ),
        ),
        migrations.AlterField(
            model_name="patientstudioassignment",
            name="reason",
            field=models.TextField(
                blank=True, help_text="可选的转移原因说明。", verbose_name="转移原因"
            ),
        ),
        migrations.AlterField(
            model_name="patientstudioassignment",
            name="start_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="归属开始时间。",
                verbose_name="开始时间",
            ),
        ),
        migrations.AlterField(
            model_name="patientstudioassignment",
            name="studio",
            field=models.ForeignKey(
                help_text="患者当前归属的工作室。",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_assignments",
                to="users.doctorstudio",
                verbose_name="工作室",
            ),
        ),
        migrations.CreateModel(
            name="ConversationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "conversation_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "患者会话"), (2, "内部会话")],
                        default=1,
                        help_text="会话类型快照。",
                        verbose_name="会话类型",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        help_text="本次会话分段的开始时间。", verbose_name="开始时间"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        help_text="本次会话分段的结束时间。", verbose_name="结束时间"
                    ),
                ),
                (
                    "message_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="本次会话分段内的消息数量。",
                        verbose_name="消息数量",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="会话分段所属的会话。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="chat.conversation",
                        verbose_name="会话",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="该会话分段所属的患者。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_sessions",
                        to="users.patientprofile",
                        verbose_name="患者",
                    ),
                ),
            ],
            options={
                "verbose_name": "会话分段",
                "verbose_name_plural": "会话分段",
                "indexes": [
                    models.Index(
                        fields=["patient", "start_at"],
                        name="idx_chat_sess_patient_start",
                    ),
                    models.Index(
                        fields=["conversation", "start_at"],
                        name="idx_chat_sess_conv_start",
                    ),
                    models.Index(
                        fields=["patient", "conversation_type", "start_at"],
                        name="idx_chat_sess_patient_type",
                    ),
                ],
            },
        ),
    ]
