# Generated by Django 5.2.8 on 2025-12-02 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0012_remove_patientprofile_device_sn"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text='【说明】程序调用用的标识，如 "about_us"、"user_agreement"、"privacy_policy"、"informed_consent"；创建后请勿随意修改。',
                        max_length=50,
                        unique=True,
                        verbose_name="唯一标识 Key",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="【说明】文案标题，例如“用户协议”。",
                        max_length=100,
                        verbose_name="标题",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="【说明】支持 Markdown 语法，自动渲染为 HTML；可使用标题、列表、加粗等格式。",
                        verbose_name="正文内容（Markdown）",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text='【说明】可选版本号，例如 "1.0"、"2025.01"。',
                        max_length=20,
                        verbose_name="版本号",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="【说明】控制该文案是否对前端可见。",
                        verbose_name="是否启用",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统文案/协议",
                "verbose_name_plural": "系统文案/协议",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "反馈问题"), (2, "提出建议")],
                        default=1,
                        verbose_name="反馈类型",
                    ),
                ),
                ("content", models.TextField(max_length=500, verbose_name="反馈内容")),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="联系方式"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "待处理"), (2, "处理中"), (3, "已解决")],
                        default=1,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="users.patientprofile",
                        verbose_name="患者",
                    ),
                ),
            ],
            options={
                "verbose_name": "意见反馈",
                "verbose_name_plural": "意见反馈",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FeedbackImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="feedback/%Y/%m/", verbose_name="图片"),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="business_support.feedback",
                        verbose_name="反馈",
                    ),
                ),
            ],
            options={
                "verbose_name": "反馈图片",
                "verbose_name_plural": "反馈图片",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "sn",
                    models.CharField(
                        db_index=True,
                        help_text="【业务说明】设备唯一物理标识；【来源】扫描字段 sn；【示例】ZK204X...",
                        max_length=64,
                        unique=True,
                        verbose_name="设备SN码",
                    ),
                ),
                (
                    "imei",
                    models.CharField(
                        blank=True,
                        help_text="【业务说明】蜂窝网络标识，如有则必须唯一；【来源】扫描字段 imei",
                        max_length=64,
                        unique=True,
                        verbose_name="IMEI",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="【来源】扫描字段 model，如 ZK204",
                        max_length=64,
                        verbose_name="硬件型号",
                    ),
                ),
                (
                    "ble_name",
                    models.CharField(
                        blank=True,
                        help_text="【来源】扫描字段 ble，用于蓝牙连接匹配",
                        max_length=64,
                        verbose_name="蓝牙广播名",
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(
                        blank=True,
                        help_text="【来源】扫描字段 version，用于判断是否需要 OTA 升级",
                        max_length=64,
                        verbose_name="固件版本",
                    ),
                ),
                (
                    "device_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "智能手表")],
                        default=1,
                        help_text="【业务说明】设备分类枚举",
                        verbose_name="设备类型",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="【业务说明】软删除标记；【用法】设备报废或误录入删除时置为False，不物理删除以保留历史数据",
                        verbose_name="是否有效",
                    ),
                ),
                (
                    "bind_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="【业务说明】发放给当前患者的时间，每次绑定更新",
                        null=True,
                        verbose_name="最近绑定时间",
                    ),
                ),
                (
                    "last_active_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="【业务说明】最后一次上报数据或心跳的时间，用于判断设备是否离线",
                        null=True,
                        verbose_name="最后活跃时间",
                    ),
                ),
                (
                    "current_patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="【业务说明】当前设备在谁手上；【用法】库存状态时为 NULL",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="users.patientprofile",
                        verbose_name="当前绑定患者",
                    ),
                ),
            ],
            options={
                "verbose_name": "智能设备",
                "verbose_name_plural": "设备库",
                "indexes": [
                    models.Index(
                        fields=["device_type", "last_active_at"],
                        name="business_su_device__efeed6_idx",
                    )
                ],
            },
        ),
    ]
