# Generated by Codex on 2026-07-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_support", "0003_seed_iwown_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceMetricReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "provider_code",
                    models.CharField(max_length=32, verbose_name="厂商编码"),
                ),
                (
                    "external_event_id",
                    models.CharField(max_length=96, verbose_name="外部事件标识"),
                ),
                (
                    "metric_type",
                    models.CharField(max_length=32, verbose_name="指标类型"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="metric_receipts",
                        to="business_support.device",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备指标接收记录",
                "verbose_name_plural": "设备指标接收记录",
            },
        ),
        migrations.AddConstraint(
            model_name="devicemetricreceipt",
            constraint=models.UniqueConstraint(
                fields=(
                    "device",
                    "provider_code",
                    "external_event_id",
                    "metric_type",
                ),
                name="uniq_device_metric_external_event",
            ),
        ),
    ]
