# Generated by Django 5.2.8 on 2026-07-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_support", "0004_devicemetricreceipt"),
        ("users", "0020_patientprofile_baseline_height_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        max_length=15,
                        verbose_name="接收手机号",
                    ),
                ),
                (
                    "content",
                    models.TextField(verbose_name="短信内容"),
                ),
                (
                    "is_success",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="是否发送成功",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_logs",
                        to="users.customuser",
                        verbose_name="请求用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "短信发送记录",
                "verbose_name_plural": "短信发送记录",
                "db_table": "business_support_sms_logs",
                "ordering": ("-created_at",),
            },
        ),
    ]
