# Generated by Django 5.2.8 on 2025-11-26 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_patientprofile_age_patientprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.BigIntegerField(blank=True, null=True, verbose_name='任务 ID')),
                ('metric_type', models.CharField(max_length=20, verbose_name='指标类型')),
                ('value_main', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='主数值')),
                ('value_sub', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='副数值')),
                ('measured_at', models.DateTimeField(verbose_name='测量时间')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='users.patientprofile', verbose_name='患者')),
            ],
            options={
                'verbose_name': '客观指标',
                'verbose_name_plural': '客观指标',
                'db_table': 'health_metrics',
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('diagnosis', models.CharField(blank=True, max_length=100, verbose_name='临床诊断')),
                ('pathology', models.CharField(blank=True, max_length=50, verbose_name='病理类型')),
                ('tnm_stage', models.CharField(blank=True, max_length=20, verbose_name='TNM 分期')),
                ('gene_mutation', models.CharField(blank=True, max_length=100, verbose_name='基因检测结果')),
                ('risk_factors', models.TextField(blank=True, verbose_name='危险因素(JSON)')),
                ('doctor_note', models.TextField(blank=True, verbose_name='阶段小结')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='users.patientprofile', verbose_name='患者')),
            ],
            options={
                'verbose_name': '病程历史',
                'verbose_name_plural': '病程历史',
                'db_table': 'health_medical_history',
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.BigIntegerField(blank=True, null=True, verbose_name='任务 ID')),
                ('symptom_type', models.CharField(max_length=20, verbose_name='症状类型')),
                ('level_score', models.IntegerField(blank=True, null=True, verbose_name='程度评分')),
                ('detail_json', models.JSONField(blank=True, null=True, verbose_name='详情 JSON')),
                ('recorded_at', models.DateTimeField(blank=True, null=True, verbose_name='记录时间')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to='users.patientprofile', verbose_name='患者')),
            ],
            options={
                'verbose_name': '主观症状',
                'verbose_name_plural': '主观症状',
                'db_table': 'health_symptom_logs',
            },
        ),
        migrations.CreateModel(
            name='ClinicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='发生日期')),
                ('event_type', models.PositiveSmallIntegerField(choices=[(1, '门诊'), (2, '住院'), (3, '复查')], verbose_name='事件类型')),
                ('hospital_name', models.CharField(blank=True, max_length=100, verbose_name='就诊医院')),
                ('department_name', models.CharField(blank=True, max_length=50, verbose_name='就诊科室')),
                ('description', models.TextField(blank=True, verbose_name='诊疗经过')),
                ('files_json', models.JSONField(blank=True, null=True, verbose_name='附件 URL 集合')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('created_by_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_events', to='users.doctorprofile', verbose_name='记录医生')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_events', to='users.patientprofile', verbose_name='患者')),
            ],
            options={
                'verbose_name': '临床诊疗事件',
                'verbose_name_plural': '临床诊疗事件',
                'db_table': 'health_clinical_events',
                'indexes': [models.Index(fields=['patient', 'event_date'], name='idx_patient_event')],
            },
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='检查日期')),
                ('report_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CT'), (2, '血常规'), (3, '生化'), (4, '基因'), (5, '处方')], null=True, verbose_name='报告类型')),
                ('image_urls', models.JSONField(verbose_name='图片 URL 列表')),
                ('ocr_text', models.TextField(blank=True, verbose_name='OCR 文本')),
                ('interpretation', models.TextField(blank=True, verbose_name='解读结论')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_reports', to='users.patientprofile', verbose_name='患者')),
            ],
            options={
                'verbose_name': '检查报告',
                'verbose_name_plural': '检查报告',
                'db_table': 'health_test_reports',
                'indexes': [models.Index(fields=['patient', 'report_date'], name='idx_patient_date')],
            },
        ),
    ]
