# Generated by Django 5.2.8 on 2025-11-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='surgery_info',
            field=models.TextField(blank=True, verbose_name='手术信息'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='risk_factors',
            field=models.TextField(blank=True, verbose_name='危险因素标签'),
        ),
    ]
