# Generated by Django 5.2.8 on 2025-12-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0002_medicalhistory_surgery_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetric',
            name='source',
            field=models.CharField(choices=[('device', '设备'), ('manual', '手动')], default='device', max_length=20, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='healthmetric',
            name='metric_type',
            field=models.CharField(choices=[('blood_pressure', '血压'), ('blood_oxygen', '血氧'), ('heart_rate', '心率'), ('steps', '步数'), ('weight', '体重')], max_length=20, verbose_name='指标类型'),
        ),
    ]
