# Generated by Django 5.2.8 on 2025-12-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0003_healthmetric_source_alter_healthmetric_metric_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmetric',
            name='metric_type',
            field=models.CharField(choices=[('blood_pressure', '血压'), ('blood_oxygen', '血氧'), ('heart_rate', '心率'), ('steps', '步数'), ('weight', '体重'), ('physical_performance', '体能评分 (ECOG)'), ('sleep_quality', '睡眠质量'), ('appetite', '食欲评分'), ('psychological_distress', '心理痛苦评分'), ('sputum_color', '痰色'), ('cough', '咳嗽'), ('dyspnea', '呼吸困难 (mMRC)'), ('pain_incision', '疼痛-胸口术口'), ('pain_shoulder', '疼痛-肩部'), ('pain_bone', '疼痛-骨头'), ('pain_head', '疼痛-头')], max_length=50, verbose_name='指标类型'),
        ),
        migrations.AlterField(
            model_name='healthmetric',
            name='value_main',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='主数值'),
        ),
    ]
