# Generated by Django 5.2.8 on 2025-12-14 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0003_alter_healthmetric_metric_type'),
        ('health_data', '0004_alter_healthmetric_metric_type_and_more'),
    ]

    operations = [
    ]
