# Generated by Django 5.2.8 on 2025-12-18 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_questionnaire_remove_planitem_followup_and_more'),
        ('health_data', '0007_healthmetric_created_at_healthmetric_updated_at'),
        ('users', '0012_remove_patientprofile_device_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptomlog',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='patient',
        ),
        migrations.AlterField(
            model_name='healthmetric',
            name='metric_type',
            field=models.CharField(choices=[('blood_pressure', '血压'), ('blood_oxygen', '血氧'), ('heart_rate', '心率'), ('steps', '步数'), ('weight', '体重'), ('body_temperature', '体温')], max_length=50, verbose_name='指标类型'),
        ),
        migrations.CreateModel(
            name='QuestionnaireSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.BigIntegerField(blank=True, null=True, verbose_name='关联任务ID')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='总分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_submissions', to='users.patientprofile', verbose_name='患者')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.questionnaire', verbose_name='问卷模板')),
            ],
            options={
                'verbose_name': '问卷提交记录',
                'verbose_name_plural': '问卷提交记录',
                'db_table': 'health_questionnaire_submissions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='文本回答')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.questionnaireoption', verbose_name='选中选项')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.questionnairequestion', verbose_name='题目')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='health_data.questionnairesubmission', verbose_name='所属提交')),
            ],
            options={
                'verbose_name': '问卷回答明细',
                'verbose_name_plural': '问卷回答明细',
                'db_table': 'health_questionnaire_answers',
            },
        ),
        migrations.DeleteModel(
            name='ClinicalEvent',
        ),
        migrations.DeleteModel(
            name='SymptomLog',
        ),
        migrations.DeleteModel(
            name='TestReport',
        ),
    ]
