# Generated by Django 5.2.8 on 2025-12-18 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "health_data",
            "0008_remove_symptomlog_patient_remove_testreport_patient_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="healthmetric",
            name="questionnaire_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_metrics",
                to="health_data.questionnairesubmission",
                verbose_name="来源问卷提交",
            ),
        ),
    ]
