# Generated by Django 5.2.8 on 2025-12-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0009_add_questionnaire_submission_fk_to_healthmetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmetric',
            name='metric_type',
            field=models.CharField(choices=[('M_BP', '血压'), ('M_SPO2', '血氧'), ('M_HR', '心率'), ('M_STEPS', '步数'), ('M_WEIGHT', '体重'), ('M_TEMP', '体温')], max_length=50, verbose_name='指标类型'),
        ),
    ]
