# Generated by Django 5.2.8 on 2025-12-20 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_data", "0010_alter_healthmetric_metric_type"),
        ("users", "0015_patientrelation_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicalhistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "病情记录",
                "verbose_name_plural": "病情记录",
            },
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="diagnosis",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="doctor_note",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="gene_mutation",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="pathology",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="record_date",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="surgery_info",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="tnm_stage",
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="clinical_diagnosis",
            field=models.TextField(
                blank=True,
                help_text="例如：右肺上叶后段恶性肿瘤性病变并远端阻塞性肺炎",
                null=True,
                verbose_name="临床诊断",
            ),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="记录该条信息的医生或助理",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_medical_histories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="genetic_test",
            field=models.TextField(
                blank=True,
                help_text="例如：EGFR 19外显子缺失",
                null=True,
                verbose_name="基因检测",
            ),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="past_medical_history",
            field=models.TextField(
                blank=True,
                help_text="例如：高血压5年，肺结节10年，I型糖尿病",
                null=True,
                verbose_name="既往病史",
            ),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="surgical_information",
            field=models.TextField(
                blank=True,
                help_text="例如：CT引导下肺穿刺活检术",
                null=True,
                verbose_name="手术信息",
            ),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="tumor_diagnosis",
            field=models.TextField(
                blank=True,
                help_text="例如：I期肺腺癌(骨、脑转移)",
                null=True,
                verbose_name="肿瘤诊断",
            ),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_histories",
                to="users.patientprofile",
                verbose_name="所属患者",
            ),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="risk_factors",
            field=models.TextField(
                blank=True,
                help_text="例如：癌症家族史，吸烟",
                null=True,
                verbose_name="危险因素",
            ),
        ),
        migrations.AlterModelTable(
            name="medicalhistory",
            table=None,
        ),
    ]
