# Generated by Django 5.2.8 on 2025-12-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0011_alter_medicalhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmetric',
            name='metric_type',
            field=models.CharField(choices=[('M_BP', '血压'), ('M_SPO2', '血氧'), ('M_HR', '心率'), ('M_STEPS', '步数'), ('M_WEIGHT', '体重'), ('M_TEMP', '体温'), ('M_USE_MEDICATED', '用药情况')], max_length=50, verbose_name='指标类型'),
        ),
    ]
