# Generated by Django 5.2.8 on 2026-01-12 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_data", "0012_alter_healthmetric_metric_type"),
        ("users", "0016_patientprofile_remark"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="检查日期")),
                (
                    "report_type",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "CT"),
                            (2, "血常规"),
                            (3, "生化"),
                            (4, "基因"),
                            (5, "处方"),
                        ],
                        null=True,
                        verbose_name="报告类型",
                    ),
                ),
                ("image_urls", models.JSONField(verbose_name="图片 URL 列表")),
                ("ocr_text", models.TextField(blank=True, verbose_name="OCR 文本")),
                (
                    "interpretation",
                    models.TextField(blank=True, verbose_name="解读结论"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_reports",
                        to="users.patientprofile",
                        verbose_name="患者",
                    ),
                ),
            ],
            options={
                "verbose_name": "检查报告",
                "verbose_name_plural": "检查报告",
                "db_table": "health_test_reports",
                "indexes": [
                    models.Index(
                        fields=["patient", "report_date"], name="idx_patient_date"
                    )
                ],
            },
        ),
    ]
