# Generated by Django 5.2.8 on 2026-01-15 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_questionnaire_metric_type_and_reseed'),
        ('health_data', '0013_testreport'),
        ('users', '0016_patientprofile_remark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='发生日期')),
                ('event_type', models.PositiveSmallIntegerField(choices=[(1, '门诊'), (2, '住院'), (3, '复查')], verbose_name='事件类型')),
                ('hospital_name', models.CharField(blank=True, max_length=100, verbose_name='就诊医院')),
                ('department_name', models.CharField(blank=True, max_length=50, verbose_name='就诊科室')),
                ('interpretation', models.TextField(blank=True, help_text='用于诊疗记录详情展示的备注/解读内容。', verbose_name='报告备注与解读')),
                ('files_json', models.JSONField(blank=True, null=True, verbose_name='附件 URL 集合')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('created_by_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_events', to='users.doctorprofile', verbose_name='记录医生')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_events', to='users.patientprofile', verbose_name='患者')),
            ],
            options={
                'verbose_name': '临床诊疗事件',
                'verbose_name_plural': '临床诊疗事件',
                'db_table': 'health_clinical_events',
            },
        ),
        migrations.CreateModel(
            name='ReportUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_source', models.PositiveSmallIntegerField(choices=[(1, '个人中心'), (2, '复查计划'), (3, '医生后台')], default=1, help_text='用于区分个人中心/复查计划/医生端上传场景。', verbose_name='上传入口')),
                ('uploader_role', models.PositiveSmallIntegerField(choices=[(1, '患者/家属'), (2, '医生'), (3, '医生助理'), (4, '平台管理员')], default=1, help_text='用于上传人标签展示与统计口径。', verbose_name='上传人角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='用于个人中心按上传日期分组展示。', verbose_name='上传时间')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='患者删除上传记录时标记；已归档图片不删除。', null=True, verbose_name='删除时间')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_uploads', to='users.patientprofile', verbose_name='患者')),
                ('related_task', models.ForeignKey(blank=True, help_text='复查计划入口上传时，绑定对应任务用于核销。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_uploads', to='core.dailytask', verbose_name='关联复查任务')),
                ('uploader', models.ForeignKey(blank=True, help_text='指向系统账号，用于展示上传人身份。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_uploads', to=settings.AUTH_USER_MODEL, verbose_name='上传人账号')),
            ],
            options={
                'verbose_name': '报告上传批次',
                'verbose_name_plural': '报告上传批次',
                'db_table': 'health_report_uploads',
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='存储上传后的可访问地址。', max_length=500, verbose_name='图片地址')),
                ('record_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, '门诊'), (2, '住院'), (3, '复查')], help_text='诊疗记录一级类目；未归档时可为空。', null=True, verbose_name='记录类型')),
                ('report_date', models.DateField(blank=True, help_text='报告出具日期，归档时填写。', null=True, verbose_name='报告日期')),
                ('archived_at', models.DateTimeField(blank=True, help_text='医生归档图片的时间。', null=True, verbose_name='归档时间')),
                ('ocr_text', models.TextField(blank=True, help_text='用于结构化识别/搜索的文本内容。', verbose_name='OCR文本')),
                ('archived_by', models.ForeignKey(blank=True, help_text='记录实际归档操作人。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_report_images', to='users.doctorprofile', verbose_name='归档人')),
                ('checkup_item', models.ForeignKey(blank=True, help_text='复查二级类目，record_type=复查时必填。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_images', to='core.checkuplibrary', verbose_name='复查项目')),
                ('clinical_event', models.ForeignKey(blank=True, help_text='归档后关联到诊疗记录。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_images', to='health_data.clinicalevent', verbose_name='诊疗记录')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='health_data.reportupload', verbose_name='上传批次')),
            ],
            options={
                'verbose_name': '报告图片',
                'verbose_name_plural': '报告图片',
                'db_table': 'health_report_images',
            },
        ),
        migrations.AddIndex(
            model_name='clinicalevent',
            index=models.Index(fields=['patient', 'event_date'], name='idx_patient_event'),
        ),
        migrations.AddIndex(
            model_name='reportupload',
            index=models.Index(fields=['patient', 'created_at'], name='idx_report_upload_patient_date'),
        ),
        migrations.AddIndex(
            model_name='reportimage',
            index=models.Index(fields=['upload', 'record_type'], name='idx_report_image_upload_type'),
        ),
        migrations.AddIndex(
            model_name='reportimage',
            index=models.Index(fields=['report_date'], name='idx_report_image_date'),
        ),
    ]
