# Generated by Django 5.2.8 on 2026-01-15 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0014_clinicalevent_reportupload_reportimage_and_more'),
        ('users', '0016_patientprofile_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='用于归档时间展示与排序。', verbose_name='记录创建时间'),
        ),
        migrations.AlterField(
            model_name='clinicalevent',
            name='created_by_doctor',
            field=models.ForeignKey(blank=True, help_text='记录创建/归档的医生或助理。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_events', to='users.doctorprofile', verbose_name='记录医生'),
        ),
        migrations.AlterField(
            model_name='clinicalevent',
            name='department_name',
            field=models.CharField(blank=True, help_text='医生端可选填写，用于展示。', max_length=50, verbose_name='就诊科室'),
        ),
        migrations.AlterField(
            model_name='clinicalevent',
            name='event_date',
            field=models.DateField(help_text='记录发生/报告日期。', verbose_name='发生日期'),
        ),
        migrations.AlterField(
            model_name='clinicalevent',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '门诊'), (2, '住院'), (3, '复查')], help_text='用于区分门诊/住院/复查。', verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='clinicalevent',
            name='files_json',
            field=models.JSONField(blank=True, help_text='诊疗记录关联图片的 URL 列表。', null=True, verbose_name='附件 URL 集合'),
        ),
        migrations.AlterField(
            model_name='clinicalevent',
            name='hospital_name',
            field=models.CharField(blank=True, help_text='医生端可选填写，用于展示。', max_length=100, verbose_name='就诊医院'),
        ),
        migrations.AlterField(
            model_name='clinicalevent',
            name='patient',
            field=models.ForeignKey(help_text='归属患者档案，用于查询与统计。', on_delete=django.db.models.deletion.CASCADE, related_name='clinical_events', to='users.patientprofile', verbose_name='患者'),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='upload',
            field=models.ForeignKey(help_text='用于把多张图片归为同一次上传。', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='health_data.reportupload', verbose_name='上传批次'),
        ),
        migrations.AlterField(
            model_name='reportupload',
            name='patient',
            field=models.ForeignKey(help_text='用于归属患者档案与查询。', on_delete=django.db.models.deletion.CASCADE, related_name='report_uploads', to='users.patientprofile', verbose_name='患者'),
        ),
    ]
