# Generated by Django 5.2.8 on 2026-01-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_data", "0015_alter_clinicalevent_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalevent",
            name="archiver_name",
            field=models.CharField(
                default="未知",
                help_text="用于诊疗记录列表展示归档人角色名称，例如“主治医生/医生助理”。",
                max_length=50,
                verbose_name="归档人",
            ),
        ),
    ]
