# Generated by Django 5.2.8 on 2026-01-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_data", "0016_add_clinicalevent_archiver_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalevent",
            name="archiver_name",
            field=models.CharField(
                default="未知",
                help_text="用于诊疗记录列表展示归档人真实姓名，例如“小桃妖”。",
                max_length=50,
                verbose_name="归档人",
            ),
        ),
    ]
