# Generated by Django 5.2.8 on 2026-01-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_data", "0020_reportimage_tvpe_item_date_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthmetric",
            name="metric_type",
            field=models.CharField(
                choices=[
                    ("M_BP", "血压"),
                    ("M_SPO2", "血氧"),
                    ("M_HR", "心率"),
                    ("M_STEPS", "步数"),
                    ("M_WEIGHT", "体重"),
                    ("M_TEMP", "体温"),
                    ("M_USE_MEDICATED", "用药情况"),
                    ("M_CHECKUP", "复查"),
                ],
                max_length=50,
                verbose_name="指标类型",
            ),
        ),
    ]
