# Generated by Django 5.2.8 on 2026-04-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_standardfield_standardfieldalias_checkupfieldmapping_and_more"),
        ("health_data", "0022_delete_testreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportimage",
            name="ai_error_message",
            field=models.TextField(blank=True, help_text="结构化识别失败时记录错误原因。", verbose_name="AI错误信息"),
        ),
        migrations.AddField(
            model_name="reportimage",
            name="ai_model_name",
            field=models.CharField(blank=True, help_text="记录本次解析使用的模型名称。", max_length=100, verbose_name="AI模型名"),
        ),
        migrations.AddField(
            model_name="reportimage",
            name="ai_parse_status",
            field=models.CharField(choices=[("PENDING", "待解析"), ("SUCCESS", "解析成功"), ("FAILED", "解析失败")], default="PENDING", help_text="当前图片结构化识别结果状态。", max_length=16, verbose_name="AI解析状态"),
        ),
        migrations.AddField(
            model_name="reportimage",
            name="ai_parsed_at",
            field=models.DateTimeField(blank=True, help_text="本次 AI 结构化识别完成的时间。", null=True, verbose_name="AI解析时间"),
        ),
        migrations.AddField(
            model_name="reportimage",
            name="ai_structured_json",
            field=models.JSONField(blank=True, help_text="保留 AI 返回的结构化 JSON 原文。", null=True, verbose_name="AI结构化结果"),
        ),
        migrations.CreateModel(
            name="CheckupResultValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_date", models.DateField(help_text="结果对应的报告日期快照。", verbose_name="报告日期")),
                ("raw_name", models.CharField(help_text="OCR/AI 识别出的原始名称。", max_length=100, verbose_name="原始字段名")),
                ("normalized_name", models.CharField(db_index=True, help_text="由原始字段名归一化生成，用于检索与排障。", max_length=100, verbose_name="归一化字段名")),
                ("raw_value", models.TextField(blank=True, help_text="OCR/AI 识别出的原始值文本。", verbose_name="原始值文本")),
                ("value_numeric", models.DecimalField(blank=True, decimal_places=4, help_text="数值型标准字段的解析结果。", max_digits=14, null=True, verbose_name="数值结果")),
                ("value_text", models.TextField(blank=True, help_text="文本型标准字段的解析结果，如影像描述或医生解读。", verbose_name="文本结果")),
                ("unit", models.CharField(blank=True, help_text="本次报告实际使用的单位快照。", max_length=50, verbose_name="结果单位")),
                ("lower_bound", models.DecimalField(blank=True, decimal_places=4, help_text="报告参考范围下限快照。", max_digits=14, null=True, verbose_name="参考下限")),
                ("upper_bound", models.DecimalField(blank=True, decimal_places=4, help_text="报告参考范围上限快照。", max_digits=14, null=True, verbose_name="参考上限")),
                ("range_text", models.CharField(blank=True, help_text="原始参考范围文本，例如 3.5-9.5。", max_length=100, verbose_name="参考范围原文")),
                ("abnormal_flag", models.CharField(choices=[("LOW", "偏低"), ("NORMAL", "正常"), ("HIGH", "偏高"), ("UNKNOWN", "未知")], default="UNKNOWN", help_text="根据数值和上下限得出的结果状态。", max_length=16, verbose_name="异常标记")),
                ("source_type", models.CharField(choices=[("AI", "AI识别"), ("MANUAL", "人工录入"), ("MIGRATED", "孤儿重处理")], default="AI", help_text="标记结果来自 AI、人工还是孤儿重处理。", max_length=16, verbose_name="来源类型")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("checkup_item", models.ForeignKey(help_text="该结果所属检查项，例如血常规、胸部CT。", on_delete=django.db.models.deletion.PROTECT, related_name="structured_result_values", to="core.checkuplibrary", verbose_name="检查项")),
                ("patient", models.ForeignKey(help_text="冗余患者，便于按患者和字段聚合查询。", on_delete=django.db.models.deletion.CASCADE, related_name="checkup_result_values", to="users.patientprofile", verbose_name="患者")),
                ("report_image", models.ForeignKey(help_text="该结果来自哪一张报告图片。", on_delete=django.db.models.deletion.CASCADE, related_name="structured_values", to="health_data.reportimage", verbose_name="来源图片")),
                ("standard_field", models.ForeignKey(help_text="最终命中的标准字段。", on_delete=django.db.models.deletion.PROTECT, related_name="result_values", to="core.standardfield", verbose_name="标准字段")),
            ],
            options={
                "verbose_name": "结构化复查结果",
                "verbose_name_plural": "结构化复查结果",
                "db_table": "health_checkup_result_values",
                "ordering": ("-report_date", "id"),
            },
        ),
        migrations.CreateModel(
            name="CheckupOrphanField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_date", models.DateField(help_text="孤儿字段对应的报告日期。", verbose_name="报告日期")),
                ("raw_name", models.CharField(help_text="未能正式落库的原始字段名。", max_length=100, verbose_name="原始字段名")),
                ("normalized_name", models.CharField(db_index=True, help_text="匹配失败后保留的归一化字段名。", max_length=100, verbose_name="归一化字段名")),
                ("raw_value", models.TextField(blank=True, help_text="OCR/AI 识别出的原始值文本。", verbose_name="原始值文本")),
                ("value_numeric", models.DecimalField(blank=True, decimal_places=4, help_text="若能解析为数值则保留，供后续转正复用。", max_digits=14, null=True, verbose_name="数值结果")),
                ("value_text", models.TextField(blank=True, help_text="若为文本型内容则保留原文本。", verbose_name="文本结果")),
                ("unit", models.CharField(blank=True, help_text="原始识别到的单位。", max_length=50, verbose_name="结果单位")),
                ("lower_bound", models.DecimalField(blank=True, decimal_places=4, help_text="原始识别到的参考范围下限。", max_digits=14, null=True, verbose_name="参考下限")),
                ("upper_bound", models.DecimalField(blank=True, decimal_places=4, help_text="原始识别到的参考范围上限。", max_digits=14, null=True, verbose_name="参考上限")),
                ("range_text", models.CharField(blank=True, help_text="原始参考范围文本。", max_length=100, verbose_name="参考范围原文")),
                ("raw_line_text", models.TextField(blank=True, help_text="便于后台回看和排查的整行原文。", verbose_name="原始整行文本")),
                ("status", models.CharField(choices=[("PENDING", "待处理"), ("RESOLVED", "已解决"), ("IGNORED", "已忽略")], default="PENDING", help_text="当前孤儿字段的处理状态。", max_length=16, verbose_name="处理状态")),
                ("resolved_at", models.DateTimeField(blank=True, help_text="孤儿字段被自动或人工解决的时间。", null=True, verbose_name="解决时间")),
                ("notes", models.TextField(blank=True, help_text="后台处理时的附加说明。", verbose_name="处理备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("checkup_item", models.ForeignKey(help_text="孤儿字段所属检查项。", on_delete=django.db.models.deletion.PROTECT, related_name="orphan_fields", to="core.checkuplibrary", verbose_name="检查项")),
                ("patient", models.ForeignKey(help_text="冗余患者，便于按患者检索孤儿字段。", on_delete=django.db.models.deletion.CASCADE, related_name="checkup_orphan_fields", to="users.patientprofile", verbose_name="患者")),
                ("report_image", models.ForeignKey(help_text="孤儿字段来自哪一张报告图片。", on_delete=django.db.models.deletion.CASCADE, related_name="orphan_fields", to="health_data.reportimage", verbose_name="来源图片")),
                ("resolved_result_value", models.ForeignKey(blank=True, help_text="孤儿字段转正后对应的正式结果记录。", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resolved_orphan_fields", to="health_data.checkupresultvalue", verbose_name="解决后正式结果")),
                ("resolved_standard_field", models.ForeignKey(blank=True, help_text="补齐 alias 或映射后最终落到哪个标准字段。", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resolved_orphan_fields", to="core.standardfield", verbose_name="解决后标准字段")),
            ],
            options={
                "verbose_name": "结构化孤儿字段",
                "verbose_name_plural": "结构化孤儿字段",
                "db_table": "health_checkup_orphan_fields",
                "ordering": ("-report_date", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="checkupresultvalue",
            constraint=models.UniqueConstraint(fields=("report_image", "standard_field"), name="uniq_report_image_standard_field"),
        ),
        migrations.AddIndex(
            model_name="checkupresultvalue",
            index=models.Index(fields=["patient", "standard_field", "report_date"], name="idx_result_patient_field_date"),
        ),
        migrations.AddIndex(
            model_name="checkupresultvalue",
            index=models.Index(fields=["checkup_item", "report_date"], name="idx_result_checkup_date"),
        ),
        migrations.AddIndex(
            model_name="checkuporphanfield",
            index=models.Index(fields=["normalized_name", "status"], name="idx_orphan_norm_status"),
        ),
        migrations.AddIndex(
            model_name="checkuporphanfield",
            index=models.Index(fields=["patient", "report_date"], name="idx_orphan_patient_date"),
        ),
        migrations.AddConstraint(
            model_name="checkuporphanfield",
            constraint=models.UniqueConstraint(
                fields=("report_image", "normalized_name"),
                name="uniq_orphan_report_image_norm_name",
            ),
        ),
    ]
